### ISSUE TITLE
Tortollan minigame buttons appear in both pet and action bar

### ISSUE THREAD

**Issue by Feichtmeier** [GoldpawsStuff/AzeriteUI#1]
Bfa version of the addon
Alpha version https://github.com/GoldpawsStuff/AzeriteUI/releases/tag/2.0.362-Alpha

![Bildschirmfoto von 2020-06-29 18-21-42](https://user-images.githubusercontent.com/15329494/86031489-2cbff780-ba36-11ea-9cb8-3da6de3a0ded.png)

And thanks for making this awesome addon!

**Comment by goldpaw** [comment]
Yeah, known issue. Some quests puts us in a situation that counts both as a vehicle and a pet. Trying to work out a way to avoid this without hiding something we actually need to see!

**Comment by goldpaw** [comment]
Should be fixed in the latest alpha-tagged builds from curseforge/twitch, and from the github versions. Tested both on live retail realms and with my level 90 hunter that just started leveling through the WoD zones. Pet bar seem to appear when it should, and not duplicate in world quests.

**Comment by Feichtmeier** [comment]
![Bildschirmfoto von 2020-07-06 23-20-35](https://user-images.githubusercontent.com/15329494/86646568-a714ec80-bfdf-11ea-8613-6ee78fa0c906.png)
Works (ofc it does :))
Thank you very much goldpaw!
