### ISSUE TITLE
What is "Use our frames"?

### ISSUE THREAD

**Issue by JasonQWJ** [GoldpawsStuff/AzeriteUI#10]
No more Blizzard raid frames. We tried having it compatible for a while, it didn't work out. Use our frames, or another 3rd party raid frame addon like Grid.

### What is "Use our frames"?
I have to use 2.0.380 to get the farm：
![WoWScrnShot_080920_000335](https://user-images.githubusercontent.com/18637996/89714825-08abea80-d9d4-11ea-90a2-05852dbfd462.jpg)

Are the red boxes our farmers? Is it in 2.0.385?

**Comment by goldpaw** [comment]
No I misunderstood, I thought we were talking about the blizzard raid frames. My bad. 

This problem will be fixed in the next update!

**Comment by goldpaw** [comment]
Fixed in 2.0.386-RC!
