### ISSUE TITLE
BattleGround Issue part 2

### ISSUE THREAD

**Issue by Tr4m4h4wK** [GoldpawsStuff/AzeriteUI#100]
Not sure if the update improved anything. Before the update I was able to occasionally get into battleground by hitting blizzard window to enter battle.. i would still say failure was about 70-80%, now instead of the blizzard window displaying when queue pops, it shows this red text "You can now enter a new battleground, right-click the green eye on the minimap to enter or leave".
I can't seem to find the minimap button. and kudos to your fast responses! i love this ui! cheers!
![Screenshot_4](https://user-images.githubusercontent.com/67484350/119245501-64003100-bb3f-11eb-91eb-78ca180b03b0.png)

**Comment by goldpaw** [comment]
No minimap eye? lol. well. I knew there was something I'd forgotten.

**Comment by goldpaw** [comment]
Hopefully the minimap bg eye is back in 3.2.488-RC. I added it, but it is untested. I have no char high enough on bc realms.
