### ISSUE TITLE
Lua Error BCC

### ISSUE THREAD

**Issue by thedukegr** [GoldpawsStuff/AzeriteUI#102]
### Make sure you can check all these boxes  

- [x ] I have the latest addon version available from CurseForge.
- [ x] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ x] Classic 
- [ ] Retail 
	- [ ] Battle for Azeroth
	- [ ] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [x] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [x] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [x] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ x] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  

Message: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: QuestTimerFrame:SetPoint.
Time: Wed Jun  9 00:22:07 2021
Count: 2
Stack: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: QuestTimerFrame:SetPoint.
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@Interface\FrameXML\UIParent.lua"]:2472: in function `UIParentManageFramePositions'
[string "@Interface\FrameXML\UIParent.lua"]:1816: in function <Interface\FrameXML\UIParent.lua:1803>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:2526: in function `UIParent_ManageFramePositions'
[string "@Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetBelowMinimapFrame.lua"]:25: in function `layoutFunc'
[string "@Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:225: in function `UpdateWidgetSetContainerLayout'
[string "@Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:318: in function `ProcessWidgetSet'
[string "@Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:340: in function `UpdateAllWidgets'
[string "@Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:33: in function <...dOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:31>

Locals: (*temporary) = QuestTimerFrame {
 0 = <userdata>
 SetPoint = <function> defined =[C]:-1
 OnBackdropLoaded = <function> defined @Interface\SharedXML\Backdrop.lua:239
 Center = <unnamed> {
 }
 numTimers = 0
 GetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:477
 SetupTextureCoordinates = <function> defined @Interface\SharedXML\Backdrop.lua:301
 OnBackdropSizeChanged = <function> defined @Interface\SharedXML\Backdrop.lua:269
 HasBackdropInfo = <function> defined @Interface\SharedXML\Backdrop.lua:365
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:509
 RightEdge = <unnamed> {
 }
 backdropInfo = <table> {
 }
 BottomEdge = <unnamed> {
 }
 GetEdgeSize = <function> defined @Interface\SharedXML\Backdrop.lua:275
 BottomLeftCorner = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:381
 SetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:416
 ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:369
 TopRightCorner = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:496
 GetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:434
 TopLeftCorner = <unnamed> {
 }
 SetupPieceVisuals = <function> defined @Interface\SharedXML\Backdrop.lua:333
 SetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:486
 LeftEdge = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @Interface\SharedXML\Backdrop.lua:353
}
(*temporary) = "TOPRIGHT"
(*temporary) = "MinimapCluster"
(*temporary) = "BOTTOMRIGHT"
(*temporary) = 0
(*temporary) = 0

### Steps to reproduce  
Reload UI

**Comment by goldpaw** [comment]
Should be fixed in 3.2.497-RC, available soon'ish on curseforge.
