### ISSUE TITLE
Healthbars under Nameplates disappear after cast 

### ISSUE THREAD

**Issue by Denixerianer** [GoldpawsStuff/AzeriteUI#104]
### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- Live Realms
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [x] Shadowlands 
- Public Test Realm 
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [ ] Shadowlands 

### What addon theme(s) does it happen in?  

- [x] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [x] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [x] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [x] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior

**Comment by Denixerianer** [comment]
When attacking a target the healthnumbers are shown beneath the nameplate. If they finish a cast its gone until you deselect and select the target again or change target and then back

**Comment by Denixerianer** [comment]
Doesnt happen always i should add. I tried figuring out what it could be caused by but i dont know.

**Comment by goldpaw** [comment]
Yeah, I'm aware. Was wondering when somebody else would notice it too! ;) 
I haven't looked much into it, yet. But definitely connected to the juggling of elements when casts happen, I think. I'll probably just rewrite the whole show/hide part of the health numbers rather than search forever for the problem. Faster. :)

**Comment by Denixerianer** [comment]
Maybe you could make it that on a cast the health numbers dont disappear but are just left behind the castbar. So while the castbar is active the numbers are also still active but just behind the castbar. Just a thought. Thx for the answer am loving the addon :)
