### ISSUE TITLE
Cooldown sometimes doesnt show

### ISSUE THREAD

**Issue by Denixerianer** [GoldpawsStuff/AzeriteUI#106]
### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- Live Realms
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [x] Shadowlands 
- Public Test Realm 
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [ ] Shadowlands 

### What addon theme(s) does it happen in?  

- [x] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [x] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [x] No 

### What classes does it happen on?  

- [x] Death Knight 
- [x] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior

**Comment by Denixerianer** [comment]
Sometimes the cooldowntext on one or more button doesnt show seems to be random only tested it on dk, dh and pala dunno about the other classes guessing its the same there.

**Comment by goldpaw** [comment]
The UI hides really short cooldowns, but is supposed to reshow the cooldown numbers again later. This is what bugs out sometimes, it seems. Happens a LOT on the quest in Maldraxxus where you ride that snapdragon thingie. 

Looking into it!

**Comment by Denixerianer** [comment]
okay ty for the answer looking forward to it  :) 👍
