### ISSUE TITLE
Error when touching objectives in Silvershard Mines

### ISSUE THREAD

**Issue by AyissaCrowett** [GoldpawsStuff/AzeriteUI#116]
## The problem  

Whenever I reach an objective in Silvershard mines it throws an error like in the picture below. It may have to do with the bar filling up on the bottom right, I assume? It may happen in other BG's too but I haven't been able to test it yet.

### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- Live Realms
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [x] Shadowlands 
- Public Test Realm 
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [ ] Shadowlands 

### What addon theme(s) does it happen in?  

- [ ] Azerite 
- [x] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [x] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [x] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [x] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  

![Screenshot 2021-09-06 193344](https://user-images.githubusercontent.com/90224219/132265756-0c465ae5-ec3c-43d0-b1b2-88a50924ae94.png)

### Steps to reproduce  

Every time I enter a mine cart objective in Silvershard Mines I get the error in the picture above.

### Expected behaviour  

There should be no error.

### Actual behaviour  

I get the error.

**Comment by HoneyBearNathan** [comment]
bump. I got the same issue A LOT in eye of the storm and i had to disable azerite ui to even play

**Comment by goldpaw** [comment]
Fixed in 3.2.511-Release. For both themes, as it would occur in both depending on switching order.
