### ISSUE TITLE
Lua Error involving back-end

### ISSUE THREAD

**Issue by HoneyBearNathan** [GoldpawsStuff/AzeriteUI#118]
### Make sure you can check all these boxes  

- [ x] I have the latest addon version available from CurseForge.
- [ ] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- Live Realms
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [x ] Shadowlands 
- Public Test Realm 
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [ ] Shadowlands 

### What addon theme(s) does it happen in?  

- [ x] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [ x] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [x ] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ x] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  

https://pastebin.com/KL24H3fV

### Steps to reproduce  

not sure

### Expected behaviour  

don't know since I don't notice anything broken but the game is saying something is. Sorry man

### Actual behaviour  

Whenever I load a character or /reload this lua error shows up.

**Comment by goldpaw** [comment]
It has something to do with how AzeriteUI positions the Narcissus minimap button. Guess he must've changed something and I didn't notice. I'll get it fixed! :)
