### ISSUE TITLE
Three diamonds appearing to left of Warlock

### ISSUE THREAD

**Issue by mjtroyer** [GoldpawsStuff/AzeriteUI#12]
Three white diamonds are appearing to the left of my warlock. This does not happen while using my evoker in dragonflight. AzeriteUI is using the latest version and is the only add on enabled.

Screenshot: https://imgur.com/a/VPyRevJ

**Comment by mjtroyer** [comment]
Version 4.0.13

**Comment by Goldpaw** [comment]
Seems to be a faulty texture on the class resource system. I have a vague memory of having fixed this, but I'll look into it!

**Comment by Goldpaw** [comment]
Found the bug, I switched the backdrop and point texture by accident, causing it to be all messed up. Fix coming in today's next update!

**Comment by mjtroyer** [comment]
Thank you!!
