### ISSUE TITLE
Autopicker Weakaura error

### ISSUE THREAD

**Issue by Imawesome1776** [GoldpawsStuff/AzeriteUI#122]
### Make sure you can check all these boxes  

- [x ] I have the latest addon version available from CurseForge.
- [ x] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- Live Realms
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [x ] Shadowlands 
- Public Test Realm 
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [ ] Shadowlands 

### What addon theme(s) does it happen in?  

- [x ] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [x ] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [x ] No 

### What classes does it happen on?  

- [x ] Death Knight 
- [x ] Demon Hunter 
- [ ] Druid 
- [x ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  
 Weakaura Error  https://ghostbin.com/uY1ZK    had 2 pages of error data so there are 2 pastes from the error code

### Steps to reproduce  

This pops up whenever i start a key....i am using a weakaura to pick my anima powers and this error pops up every time i start a key and will not pick the anima powers if AzeriteUI is enabled
### Expected behaviour  

When using the Weakaura picking an anima power should be instant and automatic
### Actual behaviour  

Instead of picking the power it just displays a new error(or maybe the same one as in the link) and leaves me to manually select my power

**Comment by Imawesome1776** [comment]
is anyone going to get a resolution or a fix for this???

**Comment by goldpaw** [comment]
There might be an issue with the quest tracker module in azeriteui that somehow makes it impossible to select anima powers in combat, and that might be related to this. I have noticed it, but not pinpointed the origin of it yet. Apart from that, I have no idea. Not using weakauras.
