### ISSUE TITLE
User driven fork

### ISSUE THREAD

**Issue by Konglomneshued** [GoldpawsStuff/AzeriteUI#125]
**What WoW version do you wish to see this feature in?**
- All versions
- [ X ] Classic Era
- [ X ] Burning Crusade Classic
- [ X ] Shadowlands

From what I have read on the FAQ as well as developer responses on reddit, you the developers really don't care what the users of your addon want, need, or suggest.  Quick to shut down any suggestions or complaints because they aren't what you want.

That's fine if you're making an addon just for yourself and some friends, but a lot of people want to scale parts of the UI down or move them for very justifiable reasons and you're clearly opposed to meeting the needs of your users for this addon.  It would be very nice to have a fork of this addon dedicated to user friendliness and customizability.  Everyone is different and has different needs and desires for how they want something organized.

**Comment by goldpaw** [comment]
/setscale x

Replace x with a number from 0.5 to 1.5. This functionality has been there for a while. Patrons all knew about it. 

What you refer to as "you, the developers". Is me, Lars Norberg, a single person coding a fan addon. Not a company, not a team, not a bunch of people working for somebody. Just a dude maintaining a fan project for a game he plays, sharing it with the world. 

And please tone down the emotional outbursts.
