### ISSUE TITLE
Minimap rotation causing HandyNotes plugins to break. 

### ISSUE THREAD

**Issue by Edvorn** [GoldpawsStuff/AzeriteUI#13]
## The problem  
When using Handynotes in classic and retail enabling the minimap rotation causes the Handynotes minimap icons display to break. Without minimap rotation the icons display just fine. additionally with Azerite unloaded and minimap rotation turned on the icons display correctly in the default minimap.

### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge/Overwolf/Twitch.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### What addon release version(s) does it happen in?  
- If you have manually chosen a release type in the Twitch client, please tell me which one:
	- [ ] Alpha
	- [ ] Beta
	- [x] Release (CurseForge/Twitch default)

### What game version(s) does it happen in?  

- [x] Classic 
- [ ] Classic (Public Test Realm) 
- [x] Battle for Azeroth 
- [ ] Battle for Azeroth (Public Test Realm) 

### Does this happen with NO other addons enabled?  

- [ ] Yes 
- [ ] No 

### What classes does it happen on?  

- [x] Death Knight 
- [x] Demon Hunter 
- [x] Druid 
- [x] Hunter 
- [x] Mage 
- [x] Monk 
- [x] Paladin 
- [x] Priest 
- [x] Rogue 
- [x] Shaman 
- [x] Warlock 
- [x] Warrior 

### Steps to reproduce  

In Classic Load Azerite UI, Handynotes, and handynotes NPCs (Classic)
goto any place where vender NPC's are, disable minimap rotation, reload ui. Then enable rotation and reload ui
Reproduce steps with Azerite unloaded

In Retail Load Azerite UI, Handynotes, and Handynotes Dungeon Locations 
goto Stormwind and stand near Stockades (or Orgrimmar and stand near Ragefire), disable minimap rotation, reload ui. Then enable rotation and reload ui
Reproduce steps with Azerite unloaded

**Comment by goldpaw** [comment]
I also notice this behavior in Gathermate and Questie for classic. Any addon putting icons on the Minimap is affected, in both versions of the UI it seems.

**Comment by goldpaw** [comment]
I'm also noticing now during my testing that even after a 2nd reload after disabling rotating minimap, the pin location aren't correct. They move slightly when we move. They're not picking up on the changed minimap size of the addon. 

This'll take some time! :D

**Comment by goldpaw** [comment]
Hopefully fixed in 2.0.389. Added extra method calls to try to force the rotation update for addons adding their own pins to the Minimap. Still keeping an eye on the issue.
