### ISSUE TITLE
Quest tracker error everytime I log in

### ISSUE THREAD

**Issue by Stormhand81** [GoldpawsStuff/AzeriteUI#131]
## The problem  
Everytime I log in now after last updates, I get this error message, and both the questtracker as the minimap is misplaced, along with some other minor issues.
  

### Make sure you can check all these boxes  

- [X ] I have the latest addon version available from CurseForge.
- [ X] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- Live Realms
	- [ ] Classic Era 
	- [X ] Burning Crusade Classic 
	- [ ] Shadowlands 
- Public Test Realm 
	- [ ] Classic Era 
	- [X ] Burning Crusade Classic 
	- [ ] Shadowlands 

### What addon theme(s) does it happen in?  

- [X ] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [X ] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [X ] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [X ] Hunter 
- [X ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  
Message: ...-end\modules\blizzard\blizzard-objectivestracker.lua:451: attempt to index global 'layout' (a nil value)
Time: Tue May  3 16:11:22 2022
Count: 2
Stack: ...-end\modules\blizzard\blizzard-objectivestracker.lua:451: attempt to index global 'layout' (a nil value)
[string "@Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-objectivestracker.lua"]:451: in function `UpdateClassicTrackerPosition'
[string "@Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-objectivestracker.lua"]:279: in function <...-end\modules\blizzard\blizzard-objectivestracker.lua:277>
[string "=[C]"]: in function `SetPoint'
[string "@Interface_TBC\FrameXML\UIParent.lua"]:2539: in function `UIParentManageFramePositions'
[string "@Interface_TBC\FrameXML\UIParent.lua"]:1831: in function <Interface_TBC\FrameXML\UIParent.lua:1818>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_TBC\FrameXML\UIParent.lua"]:2550: in function `UIParent_ManageFramePositions'
[string "@Interface\FrameXML\FloatingChatFrame.lua"]:1273: in function `FCF_RestorePositionAndDimensions'
[string "@Interface\FrameXML\FloatingChatFrame.lua"]:225: in function `FloatingChatFrame_Update'
[string "@Interface\FrameXML\FloatingChatFrame.lua"]:112: in function `FloatingChatFrame_OnEvent'
[string "*:OnEvent"]:2: in function <[string "*:OnEvent"]:1>

Locals: self = <table> {
 SetRelativeScale = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:419
 ForAll = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\module.lua:725
 UnregisterAllEvents = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:184
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\module.lua:716
 DisableUIWidget = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\blizzard.lua:1882
 StyleClassicLog = <function> defined @Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-objectivestracker.lua:235
 EnableUIWidget = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\blizzard.lua:1859
 RegisterKeyword = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:371
 StyleRetailTracker = <function> defined @Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-objectivestracker.lua:470
 IsModuleAvailable = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\module.lua:813
 CreateTextureCache = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:410
 GetFrame = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:403
 IsEnabled = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\module.lua:764
 Fire = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:54
 StyleUIWidget = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\blizzard.lua:1905
 InitRetailTracker = <function> defined @Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-objectivestracker.lua:507
 IsInitialized = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\module.lua:760
 UnregisterMessage = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:299
 InitAlphaDriver = <function> defined @Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-objectivestracker.lua:551
 UnregisterAllMessages = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:347
 layout = <table> {
 }
 OnInit = <function> defined @Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-objectivestracker.lua:630
 RegisterUnitEvent = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:106
 DisableUIMenuPage = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\blizzard.lua:1958
 UpdateTrackerSizeAndScale = <function> defined @Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-objectivestracker.lua:486
 SetAspectRatio = <f

### Steps to reproduce  
Just log in game.

### Expected behaviour  
No lua error messages and no minimap + questtracker misplaced

### Actual behaviour  
Minimap and questtracker are misplaced.

**Comment by Goldpaw** [comment]
Well I can't log in. Long story! ;)

But the error report is spot on, points me straight to the problem. I'll get it fixed!

**Comment by Stormhand81** [comment]
Excellent, I'm glad I did this report correctly!

Looking forward to this fix. Thanks a lot!

Em ter., 3 de mai. de 2022 16:38, Lars Norberg ***@***.***>
escreveu:

**Comment by Goldpaw** [comment]
Should be fixed in 3.2.536-Release, which is on its way out to the various pages and clients now!
