### ISSUE TITLE
AzeriteUI not activating.

### ISSUE THREAD

**Issue by maxjonata** [GoldpawsStuff/AzeriteUI#133]
## The problem
AzeriteUI enabled but not activated.

### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- Live Realms
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [x] Shadowlands 
- Public Test Realm 
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [ ] Shadowlands 

### What addon theme(s) does it happen in?  

- [x] Azerite 
- [x] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [ ] Yes 
- [x] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [x] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [x] Shaman 
- [x] Warlock 
- [ ] Warrior 
Couldnt test in the others, i only have these two

### Steps to reproduce  

When i configure my addons in game i have to first activate azeriteUI then activate one addon each time or the azeriteUI will not activate although enabled in addons window (neither work the /go azerite or /go legacy).

**Comment by Goldpaw** [comment]
If you're using MoveAnything, disable that. AzeriteUI is incompatible with it.
