### ISSUE TITLE
Bagbutton lua error on load

### ISSUE THREAD

**Issue by Dibbli** [GoldpawsStuff/AzeriteUI#144]
## The problem  
Upon loading into wow, with or without every other addon disabled i get a lua error, nothing much buts its quite annoying

### Make sure you can check all these boxes  

- [x ] I have the latest addon version available from CurseForge.
- [ x] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- Live Realms
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [x ] Shadowlands 
- Public Test Realm 
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [ ] Shadowlands 

### What addon theme(s) does it happen in?  

- [x ] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [x ] Yes 
- [x ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [ x] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ x] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  

https://pst.klgrth.io/paste/8gray
and a second one that's just
Message: (null)
Time: Fri Jul 29 11:32:11 2022
Count: 4
Stack: (null)

Locals: <none>

### Steps to reproduce  
I dont know, i installed azerite UI and now ANY TIME its enabled, it does it

### Expected behaviour  
Not LUA error

### Actual behaviour  
It LUA errors

**Comment by Goldpaw** [comment]
Fixed in 3.2.544-RC which should go live on the public pages soon'ish! :)
