### ISSUE TITLE
Lua warnings in WotLK Beta 3.4.0.44930

### ISSUE THREAD

**Issue by Razorwynd** [GoldpawsStuff/AzeriteUI#145]
Trying to get my relaxing controller-based UI setup before WotLK releases and I am having trouble getting your UI to load. I get 7 lua errors.

The first of which is associated with:
...AddOns\AzeriteUI\front-end\config\api.lua:117: bad argument #1 to 'setmetatable' (table expected, got boolean)
Three associated with:
...AddOns\AzeriteUI\back-end\libraries\actionbutton.lua:1093: attempt to call method 'UpdateSpellHighlight' (a nil value)
...AddOns\AzeriteUI\back-end\libraries\actionbutton.lua:1093: attempt to call method 'UpdateSpellHighlight' (a nil value)
...AddOns\AzeriteUI\back-end\libraries\actionbutton.lua:1093: attempt to call method 'UpdateSpellHighlight' (a nil value)
Another associated with:
...\AddOns\AzeriteUI\back-end\libraries\message.lua:67: The module 'table: 0x7f7f1f22ef80' has no method named 'OnInit'!
\AddOns\AzeriteUI\front-end\core\gui.lua:1034: attempt to index local 'db' (a nil value)

And the seventh just says:
(null)

Let me know if you need screenshots.

**Comment by Goldpaw** [comment]
That should be enough to go on for now. 

WotLK support is currently experimental for this addon, since I don't have access to the WotLK beta myself. The main changes from the other classics are in the actionbars, which lands somewhere between retail and the other classics. So I'm expecting bugs of this kind at this point. 

I'll see if I can sort it out! :)

**Comment by Razorwynd** [comment]
Great! It Looks like the PTR is also on the pre patch with this version of the client so you should be able to test it out if you want. 

> That should be enough to go on for now.
> 
> WotLK support is currently experimental for this addon, since I don't have access to the WotLK beta myself. The main changes from the other classics are in the actionbars, which lands somewhere between retail and the other classics. So I'm expecting bugs of this kind at this point.
> 
> I'll see if I can sort it out! :)

Great! It Looks like the PTR is also on the pre patch with this version of the client so you should be able to test it out if you want.

**Comment by Goldpaw** [comment]
Actually I don't even own a computer capable of running the game right now, so no! Been doing updates and new addons from a chromebook, working through proxy testers for about 4-5 months now! :D

**Comment by Goldpaw** [comment]
It may or may not work better in 3.2.545-RC, which I just pushed out and may or may not become available on CurseForge and Wago shortly. 

I mainly added a lot of the missing code for actionbuttons and unitframes that are related to things the other classic clients don't have, but retail has. Like vehicles.
