### ISSUE TITLE
"fixLevel" tooltip bug

### ISSUE THREAD

**Issue by Imawesome1776** [GoldpawsStuff/AzeriteUI#147]
### Did you update to the most recent version?
- [x ] I have the latest addon version available from CurseForge or Wago.

### What game version(s) does it happen in? Choose your version and the highest expansion you own

- Live Realms
  - [ ] Classic Era / Vanilla
  - [x ] Burning Crusade Classic
  - [ ] Shadowlands (Retail)
- Public Test Realm
  - [ ] Classic Era / Vanilla
  - [ ] Burning Crusade Classic
  - [ ] Wrath of the Lich King
  - [ ] Shadowlands (Retail)
- Alpha/Beta
  - [ ] Wrath of the Lich King
  - [ ] Dragonflight

### What addon theme(s) does it happen in?

- [ x] Azerite
- [ ] Legacy
- [ ] I don't know what this means.

### Does this happen with ONLY this addon enabled?

- [ x] Yes
- [ ] No

### Does this happen with absolutely all addons (this included) disabled?

- [x ] Yes
- [ ] No

### What classes does it happen on?

- [ ] Death Knight
- [ ] Demon Hunter
- [ ] Druid
- [ ] Evoker
- [ ] Hunter
- [x ] Mage
- [ ] Monk
- [ ] Paladin
- [ ] Priest
- [ ] Rogue
- [ ] Shaman
- [ ] Warlock
- [ ] Warrior

### Actual behaviour

Up until the morning of 8/9/22 AzeriteUI was working great in TBC Classic not sure what happened on this morning but after i logged in ALL of my buttons associated with AzeriteUI disappeared, there is a minimap overlay issue, and no matter what i seem to mouse over LUA errors just constantly pop up. I am putting a screenshot of what my screen looks like after i logged in below, 
![WoWScrnShot_080922_135034](https://user-images.githubusercontent.com/93995867/183759835-c8ab5d42-7718-455e-9c5b-0db2e5344ee3.jpg)

I hope that worked....also it does this as the only addon being turned on as well...that screenshot was with ONLY azeriteUI active....it does do this with other addons also but im sure that isnt the problem. I am pasting the code i copied from when i logged in below, i hope this helps.

Message: ...eUI\front-end\modules\blizzard\blizzard-tooltips.lua:402: attempt to call global 'fixLevel' (a nil value)
Time: Tue Aug  9 13:50:21 2022
Count: 1
Stack: ...eUI\front-end\modules\blizzard\blizzard-tooltips.lua:402: attempt to call global 'fixLevel' (a nil value)
[string "@Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-tooltips.lua"]:402: in function `SetBackdrop'
[string "@Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-tooltips.lua"]:342: in function `Style'
[string "@Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-tooltips.lua"]:849: in function `StyleTooltips'
[string "@Interface\AddOns\AzeriteUI\front-end\modules\blizzard\blizzard-tooltips.lua"]:944: in function `OnEnable'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\module.lua"]:282: in function `?'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\module.lua"]:737: in function `ForAll'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\module.lua"]:252: in function `Init'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\module.lua"]:867: in function `?'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\message.lua"]:65: in function `Fire'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\event.lua"]:71: in function <...erface\AddOns\AzeriteUI\back-end\libraries\event.lua:68>

Locals: self = GameTooltip {
 0 = <userdata>
 numMoneyFrames = 2
 layoutType = "TooltipDefaultLayout"
 shoppingTooltips = <table> {
 }
 GetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:182
 BottomOverlay = <unnamed> {
 }
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:186
 updateTooltip = 0.200000
 Show = <function> defined =[C]:-1
 TooltipBackdropOnLoad = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:163
 SetFrameLevel = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:190
 hasMoney = 1
 needsReset = true
 SetBorderBlendMode = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:194
 SetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:178
 NineSlice = <unnamed> {
 }
}
backdropInfo = <table> {
 bgFile = "Interface\Tooltips\UI-Tooltip-Background"
 edgeFile = "Interface\AddOns\AzeriteUI\front-end\media\better-blizzard-border-small-alternate.tga"
 tile = false
 edgeSize = 32
 tileEdge = false
 insets = <table> {
 }
}
backdrop = <unnamed> {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface\SharedXML\Backdrop.lua:144
 Center = <unnamed> {
 }
 GetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:382
 SetupTextureCoordinates = <function> defined @Interface\SharedXML\Backdrop.lua:206
 OnBackdropSizeChanged = <function> defined @Interface\SharedXML\Backdrop.lua:174
 HasBackdropInfo = <function> defined @Interface\SharedXML\Backdrop.lua:270
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:414
 RightEdge = <unnamed> {
 }
 backdropInfo = <table> {
 }
 BottomEdge = <unnamed> {
 }
 GetEdgeSize = <function> defined @Interface\SharedXML\Backdrop.lua:180
 BottomLeftCorner = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:274
 TopRightCorner = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:339
 TopLeftCorner = <unnamed> {
 }
 SetupPieceVisuals = <function> defined @Interface\SharedXML\Backdrop.lua:238
 SetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:391
 LeftEdge = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @Interface

im hoping you can fix this for TBC Classic...i really love and enjoy your UI set up and miss it already and its only been a few hours lol

**Comment by Goldpaw** [comment]
This affects all versions of the UI, and is a result of a faulty update yesterday. I'm on it and will fix it shortly. 

I Rrenamed the issue so others might easier find it, and will redirect the duplicate bug reports to this one since it was the first.

**Comment by Goldpaw** [comment]
Should be fixed in 3.2.548-RC, which should be live on CurseForge and Wago any second now.

**Comment by Imawesome1776** [comment]
awesome thanks for your speedy reply and fix xD happy to have it back
