### ISSUE TITLE
Bosses Dialogue 

### ISSUE THREAD

**Issue by Xeltes** [GoldpawsStuff/AzeriteUI#15]
**What WoW version do you wish to see this feature in?**

- [ ] Battle for Azeroth

**Is your feature request related to a problem? Please describe.**
Hey there, I'm not sure if it is a Bug or a Feature, but I was wondering how can I make so the Dialogue from Bosses, like Raid bosses and such show up again in the Chat window. I have checked all the options i can think off and couldn't find anything in the FAQ

**Describe the solution you'd like**
I just wanna know how to be able to see the bosses dialogue in the chat window again

**Additional context**
 Love this UI, I found out about on Twitter, someone re-twitted you and I was sold after i saw how clean and amazing it looked

**Comment by goldpaw** [comment]
Chat Windows > Chat Filter > Boss Messages in our addon menu, available from the cogwheel icon in the bottom right corner beneath the minimap. Can be toggled. No bug here. If the option is missing, your versions is just too old and an update should fix it. :)
