### ISSUE TITLE
LUA Errors - Wrath of the lich king 3.4.0.45327 - Classic

### ISSUE THREAD

**Issue by nixpix76** [GoldpawsStuff/AzeriteUI#152]
## The problem
AzeriteUI does not load properly. Throws 5 LUA errors when logging on.

### Did you update to the most recent version?
- [ X ] I have the latest addon version available from CurseForge or Wago.

### What game version(s) does it happen in? Choose your version and the highest expansion you own

- Live Realms
  - [ ] Classic Era / Vanilla
  - [ ] Burning Crusade Classic
  - [ ] Shadowlands (Retail)
  - [ X ] Wrath of the Lich King Classic

### What addon theme(s) does it happen in?

- [ ] Azerite
- [ ] Legacy
- [ ] I don't know what this means.
- [ X ] The options is not there due to addon not loading at all. But it was on "Azerite" before the pre patch.

### Does this happen with ONLY this addon enabled?

- [ X ] Yes
- [ ] No

### Does this happen with absolutely all addons (this included) disabled?

- [ ] Yes
- [ X ] No

### What classes does it happen on?

- [ ] Death Knight
- [ ] Demon Hunter
- [ ] Druid
- [ ] Evoker
- [ ] Hunter
- [ ] Mage
- [ ] Monk
- [ ] Paladin
- [ ] Priest
- [ ] Rogue
- [ ] Shaman
- [ X ] Warlock
- [ ] Warrior

### Any logs, screenshots, error output, etc?
 https://pst.klgrth.io/paste/4w32k

### Steps to reproduce
Login game.

### Expected behaviour
Load and display AzeriteUI

### Actual behaviour
Throws 5 errors and doennt load.

**Comment by Thci87** [comment]
same here tauren shaman in gehennas with azerite UI

**Comment by Imawesome1776** [comment]
im having the same problem....but i cant see the azerite UI HP/Mana bar or action bars when i try to load the addon all i have on my screen are the bars from Dominos...this happens on my Mage, Warrior, Rogue, Death Knight

**Comment by JuNNeZ** [comment]
Same issue, I can add some info on the errors:

> 5x AzeriteUI\front-end\config\api.lua:117: bad argument #1 to 'setmetatable' (table expected, got boolean)
> [string "=[C]"]: in function `setmetatable'
> [string "@AzeriteUI\front-end\config\api.lua"]:117: in function `RegisterLayoutVariation'
> [string "@AzeriteUI\front-end\config\configs.lua"]:1952: in main chunk
> 
> Locals:
> (*temporary) = false
> (*temporary) = <table> {
> }
> (*temporary) = "table expected, got boolean"


and


> 4x ...zeriteUI\tinkertown\schematic-actionbars-azerite.lua:625: attempt to index local 'layout' (a nil value)
> [string "@AzeriteUI\tinkertown\schematic-actionbars-azerite.lua"]:625: in function `func'
> [string "@AzeriteUI\back-end\libraries\forge.lua"]:198: in function `Chain'
> [string "@AzeriteUI\back-end\libraries\forge.lua"]:442: in function <AzeriteUI\back-end\libraries\forge.lua:241>
> [string "=(tail call)"]: ?
> [string "@AzeriteUI\front-end\modules\custom\actionbars.lua"]:34: in function `OnInit'
> [string "@AzeriteUI\back-end\libraries\module.lua"]:238: in function `Init'
> [string "@AzeriteUI\back-end\libraries\module.lua"]:268: in function `?'
> [string "@AzeriteUI\back-end\libraries\module.lua"]:737: in function `ForAll'
> [string "@AzeriteUI\back-end\libraries\module.lua"]:252: in function `Init'
> [string "@AzeriteUI\back-end\libraries\module.lua"]:867: in function `?'
> [string "@AzeriteUI\back-end\libraries\message.lua"]:65: in function `Fire'
> [string "@AzeriteUI\back-end\libraries\event.lua"]:71: in function <AzeriteUI\back-end\libraries\event.lua:68>
> 
> Locals:
> self = <table> {
>  ForAll = <function> defined @AzeriteUI\back-end\libraries\module.lua:725
>  GetStanceButtons = <function> defined @AzeriteUI\tinkertown\schematic-actionbars-azerite.lua:662
>  UpdateFadeAnchors = <function> defined @AzeriteUI\tinkertown\schematic-actionbars-azerite.lua:877
>  modules = <table> {
>  }
>  GetOverlayFramePet = <function> defined @AzeriteUI\tinkertown\schematic-actionbars-azerite.lua:682
>  UpdateCastOnDown = <function> defined @AzeriteUI\tinkertown\schematic-actionbars-azerite.lua:968
>  ParseSavedVariables = <function> defined @AzeriteUI\back-end\libraries\db.lua:74
>  UpdateButtonCount = <function> defined @AzeriteUI\tinkertown\schematic-actionbars-azerite.lua:950
>  SpawnPetBar = <function> defined @AzeriteUI\tinkertown\schematic-actionbars-azerite.lua:409
>  NewConfig = <function> defined @AzeriteUI\back-end\libraries\db.lua:138
>  StanceButtons = <table> {
>  }
>  GetActionBarControllerPetBattle = <function> defined @AzeriteUI\back-end\libraries\actionbutton.lua:2948
>  GetFrame = <function> defined @AzeriteUI\back-end\libraries\frame.lua:403
>  IsEnabled = <function> defined @AzeriteUI\back-end\libraries\module.lua:764
>  CreateSecureUpdater = <function> defined @AzeriteUI\tinkertown\schematic-actionbars-azerite.lua:276
>  GetFadeFrame = <function> defined @AzeriteUI\tinkertown\schematic-actionbars-azerite.lua:687
>  SetDefaultTooltipStatusBarTexture = <function> defined @AzeriteUI\back-end\libraries\tooltip.lua:2579
>  GetPetButtons = <function> defined @AzeriteUI\tinkertown\schematic-actionbars-azerite.lua:667
>  IsInitialized = <function> defined @AzeriteUI\back-end\libraries\module.lua:760
>  UnregisterMessage = <function> defined @AzeriteUI\back-end\libraries\message.lua:299
>  UpdateSettings = <function> defined @AzeriteUI\tinkertown\schematic-actionbars-azerite.lua:1021
>  SetDefaultTooltipStatusBarInset = <function> defined @AzeriteUI\back-end\libraries\tooltip.lua:2540
>  frameOverlay = <unnamed> {
>  }
>  Chain = <function> defined @AzeriteUI\back-end\libraries\forge.lua:177
>  SetDefaultTooltipBackdropBorderColor = <function> defined @AzeriteUI\back-end\libraries\tooltip.lua:2522
>  db = <table> {
>  }
>  RegisterUnitEvent = <function> defined @AzeriteUI\back-end\libraries\message.lua:106
>  CreateTooltip = <function> defined @AzeriteUI\back-end\libraries\tooltip.lua:2585
>  SpawnTotemBar = <function> defined @AzeriteUI\tinkertown\schematic-actionbars-azerite.lua:482
>  GetConfig = <function> defined @AzeriteUI\back-end\libraries\db.lua:238
>  ButtonLookup = <table> {
>  }
>  GetSecureUpdater = <function> defined @AzeriteUI\front-end\core\gui.lua:1155
>  UpdateTooltipSettings = <function> defined @AzeriteUI\tinkertown\schematic-actionbars-azerite.lua:983
>  moduleLoadPriority = <table> {
>  }
>  frameOverlayPet = <unnamed> {
>  }
>  UpdateActionButtonBindings = <function> defined @AzeriteUI\back-end\libraries\actionbutton.lua:3106
>  SetDefaultTooltipStatusBarOffset = <function> defined @AzeriteUI\back-end\libraries\tooltip.lua:2548
>  OnEnable = <function> defined @AzeriteUI\front-end\modules\custom\actionbars.lua:38
>  ForAllTooltips = <function> defined @AzeriteUI\back-end\libraries\tooltip.lua:2691
>  SetDefaultTooltipBackdrop = <function> defined @AzeriteUI\back-end\libraries\tooltip.lua:2506
>  UpdateCVars = <function> defined @AzeriteUI\front-end\modules\custom\actionbars.lua:23
>  frame = <unnamed> {
>  }
>  UpdateButtonLayout = <function> defined @AzeriteUI\tinkertown\schematic-actionbars-azerite.lua:956
>  SpawnStanceBar = <function> defined @AzeriteUI\tinkertow

**Comment by delairec** [comment]
The schedule has been published on twitter, it seems that breaking bugs will be waiting until the third week of september :
![image](https://user-images.githubusercontent.com/48012472/188261404-af7b546f-02f1-4441-b9e1-6e4036c07091.png)

**Comment by nixpix76** [comment]
Thank you for bringing attention to that. Now we have something to look forward to :)

**Comment by Imawesome1776** [comment]
is that why after the last couple updates it still doesnt load properly?

**Comment by Goldpaw** [comment]
A working version of AzeriteUI for Wrath is now available, from 3.2.553-RC or higher.
