### ISSUE TITLE
3.2.550

### ISSUE THREAD

**Issue by xuesemofa** [GoldpawsStuff/AzeriteUI#153]
Message: Interface\AddOns\AzeriteUI\front-end\config\api.lua:117: bad argument #1 to 'setmetatable' (table expected, got boolean)
Time: Sat Sep  3 09:18:49 2022
Count: 1
Stack: Interface\AddOns\AzeriteUI\front-end\config\api.lua:117: bad argument #1 to 'setmetatable' (table expected, got boolean)
[string "=[C]"]: in function `setmetatable'
[string "@Interface\AddOns\AzeriteUI\front-end\config\api.lua"]:117: in function `RegisterLayoutVariation'
[string "@Interface\AddOns\AzeriteUI\front-end\config\configs.lua"]:1952: in main chunk

Locals: (*temporary) = false
(*temporary) = <table> {
}
(*temporary) = "table expected, got boolean"

**Comment by delairec** [comment]
This bug has already been reported in #152
