### ISSUE TITLE
Basic core UI elements not loading

### ISSUE THREAD

**Issue by Tr4m4h4wK** [GoldpawsStuff/AzeriteUI#155]
The basic core elements of the ui is not loading up in WoTLK Classic. Retail works great! Classic error report as follows

Message: Interface\AddOns\AzeriteUI\front-end\core\gui.lua:512: attempt to index local 'db' (a nil value)
Time: Tue Sep  6 00:44:05 2022
Count: 3
Stack: Interface\AddOns\AzeriteUI\front-end\core\gui.lua:512: attempt to index local 'db' (a nil value)
[string "@Interface\AddOns\AzeriteUI\front-end\core\gui.lua"]:512: in function `Update'
[string "@Interface\AddOns\AzeriteUI\front-end\core\gui.lua"]:443: in function <Interface\AddOns\AzeriteUI\front-end\core\gui.lua:441>
[string "=[C]"]: in function `Hide'
[string "@Interface\FrameXML\SecureHoverDriver.lua"]:168: in function <Interface\FrameXML\SecureHoverDriver.lua:112>

Locals: self = AzeriteUI_ConfigMenu_OptionsButton50 {
 0 = <userdata>
 Point = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:270
 OnBackdropLoaded = <function> defined @Interface\SharedXML\Backdrop.lua:152
 CreateStatusBar = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\statusbar.lua:808
 GetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:390
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:422
 isDown = false
 disabledTitle = "Monster Emotes"
 newbieText = "Toggles the display of boss- and monster emotes. If you're a skilled player, it is not recommended to turn these on, as some world quests and most boss encounters send important messages here.

Support wheel users relying on Dumb Boss Mods can do whatever they please, it's not like they're looking at anything else than bars anyway."
 ApplyBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:294
 SetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:282
 IsForbidden = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:320
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:409
 GetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:347
 tooltipText = "Monster Emotes"
 ArrowDown = <unnamed> {
 }
 ArrowUp = <unnamed> {
 }
 CreateSpinBar = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\spinbar.lua:867
 SetBorderBlendMode = <function> defined @Interface\SharedXML\Backdrop.lua:266
 proxyModule = "BlizzardFloaterHUD"
 NormalBackdrop = <unnamed> {
 }
 Msg = <unnamed> {
 }
 Place = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:244
 CreateTexture = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:338
 PushedBackdrop = <unnamed> {
 }
 enabledTitle = "Monster Emotes"
 SetFrameRef = <function> defined @Interface\FrameXML\SecureHandlers.lua:793
 OnBackdropSizeChanged = <function> defined @Interface\SharedXML\Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface\SharedXML\Backdrop.lua:278
 GetFrame = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:239
 optionDB = "BlizzardFloaterHUD"
 Size = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:290
 updateType = "TOGGLE_VALUE"
 GetEdgeSize = <function> defined @Interface\SharedXML\Backdrop.lua:188
 layout = <table> {
 }
 UnwrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:788
 CreateOrb = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\orb.lua:503
 CreateFontString = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:333
 Execute = <function> defined @Interface\FrameXML\SecureHandlers.lua:777
 CreateFrame = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:328
 SetupTextureCoordinates = <function> defined @Interface\SharedXML\Backdrop.lua:214
 WrapScript = <function> defined @Interface\FrameXML\SecureHandlers.lua:782
 SetupPieceVisuals = <function> defined @Interface\SharedXML\Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:399
 SetProperties = <function> defined @Interface\AddOns\AzeriteUI\back-end\

Keep up the great work, by far the best kept secret as far as custom UI's go... cheers!!

**Comment by Imawesome1776** [comment]
ya after i updated the most recent version of AzeriteUI on classic i get a hard screen cover of errors that just wont disappear i have to close the client for them to go away
