### ISSUE TITLE
Weird LUE Error

### ISSUE THREAD

**Issue by holmes1222** [GoldpawsStuff/AzeriteUI#156]
### Did you update to the most recent version?
- [x] I have the latest addon version available from CurseForge or Wago.

### What game version(s) does it happen in? Choose your version and the highest expansion you own

- Live Realms
  - [ ] Classic Era / Vanilla
  - [ ] Burning Crusade Classic
  - [ x] Shadowlands (Retail)
- Public Test Realm
  - [ ] Classic Era / Vanilla
  - [ ] Burning Crusade Classic
  - [ ] Wrath of the Lich King
  - [x ] Shadowlands (Retail)
- Alpha/Beta
  - [x ] Wrath of the Lich King
  - [ ] Dragonflight

### What addon theme(s) does it happen in?

- [x ] Azerite
- [ ] Legacy
- [ ] I don't know what this means.

### Does this happen with ONLY this addon enabled?

- [ x] Yes
- [ ] No

### Does this happen with absolutely all addons (this included) disabled?

- [x ] Yes
- [ ] No

### What classes does it happen on?

- [ ] Death Knight
- [ ] Demon Hunter
- [ ] Druid
- [ ] Evoker
- [ ] Hunter
- [x ] Mage
- [ ] Monk
- [ ] Paladin
- [ ] Priest
- [ ] Rogue
- [ ] Shaman
- [ ] Warlock
- [ ] Warrior

### Any logs, screenshots, error output, etc?
Message: ...erface\AddOns\AzeriteUI\back-end\libraries\fader.lua:361: attempt to index upvalue 'safeDebuffs' (a nil value)
Time: Tue Sep  6 10:17:01 2022
Count: 1
Stack: ...erface\AddOns\AzeriteUI\back-end\libraries\fader.lua:361: attempt to index upvalue 'safeDebuffs' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua"]:361: in function `CheckAuras'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua"]:486: in function `?'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\message.lua"]:65: in function `Fire'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\event.lua"]:71: in function <...erface\AddOns\AzeriteUI\back-end\libraries\event.lua:68>

**Comment by Goldpaw** [comment]
Already fixed, it's just not live on CurseForge yet, they're having some problems today. No updates have gone through there yet. So either wait for the most recent version (3.2.555-RC or higher) to become available on CurseForge, or download it from Wago.
