### ISSUE TITLE
Weird Debuff bug (Classic WOTLK)

### ISSUE THREAD

**Issue by Tr4m4h4wK** [GoldpawsStuff/AzeriteUI#158]
everytime i get a debuff i get a bug.. happens during thunder claps, frostbolts, and death debuffs..

report follows:

Message: ...erface\AddOns\AzeriteUI\back-end\libraries\fader.lua:361: attempt to index upvalue 'safeDebuffs' (a nil value)
Time: Wed Sep  7 22:58:39 2022
Count: 1
Stack: ...erface\AddOns\AzeriteUI\back-end\libraries\fader.lua:361: attempt to index upvalue 'safeDebuffs' (a nil value)
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua"]:361: in function `CheckAuras'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua"]:486: in function `?'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\message.lua"]:65: in function `Fire'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\event.lua"]:71: in function <...erface\AddOns\AzeriteUI\back-end\libraries\event.lua:68>

Locals: self = <table> {
 SetRelativeScale = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:419
 ForAll = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:714
 DisableGroupFading = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:277
 UnregisterAllEvents = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:184
 SetObjectAlpha = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:286
 GetUnitAura = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\aura.lua:162
 CreateFrame = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:376
 OnUpdate = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:634
 SetObjectFadeOverride = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:259
 embeds = <table> {
 }
 SetAspectRatio = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:429
 IsEventRegistered = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:207
 InitiateDelay = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:612
 CreateTextureCache = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:410
 SetObjectFadeHold = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:606
 CheckOverride = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:416
 GetFrame = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:403
 SetObjectFadeDurationIn = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:594
 ValidateTimerData = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:581
 Fire = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:54
 Embed = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:735
 CheckInstance = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:456
 ClearTimerData = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:568
 CheckVehicle = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:407
 CheckPossess = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:424
 CheckTarget = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:432
 RegisterMessage = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:276
 UnregisterMessage = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:299
 data = <table> {
 }
 GetCurrentFaderState = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:227
 CheckFocus = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:440
 DisableInstanceFading = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:268
 RegisterObjectFade = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:232
 SetObjectFadeDurationOut = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:600
 CheckGroup = <function> defined @Interface\AddOns\AzeriteUI\back

**Comment by xuesemofa** [comment]
Message: ...erface\AddOns\AzeriteUI\back-end\libraries\fader.lua:361: attempt to index upvalue 'safeDebuffs' (a nil value)
Time: Thu Sep  8 21:03:47 2022
Count: 290
Stack: ...erface\AddOns\AzeriteUI\back-end\libraries\fader.lua:361: attempt to index upvalue 'safeDebuffs' (a nil value)
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua"]:361: in function `CheckAuras'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua"]:561: in function `?'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\message.lua"]:65: in function `Fire'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\event.lua"]:71: in function <...erface\AddOns\AzeriteUI\back-end\libraries\event.lua:68>

Locals: self = <table> {
 SetRelativeScale = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:419
 achievedState = "peril"
 ForAll = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:714
 totalDurationOut = 0.750000
 elapsed = 0
 IsEventRegistered = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:207
 totalDurationHoldCounter = 0
 CheckVehicle = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:407
 currentPosition = 1
 DisableGroupFading = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:277
 UnregisterAllEvents = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:184
 GetUnitAura = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\aura.lua:162
 CheckCursor = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:318
 CreateFrame = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:376
 OnUpdate = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:634
 SetObjectFadeOverride = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:259
 SetObjectAlpha = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:286
 embeds = <table> {
 }
 totalDurationIn = 0.150000
 RegisterKeyword = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:371
 totalElapsedOut = 0
 totalElapsedIn = 0
 totalElapsed = 0
 CreateTextureCache = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:410
 SetAspectRatio = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:429
 InitiateDelay = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:612
 GetFrame = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:403
 SetObjectFadeHold = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:606
 CheckOverride = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:416
 Fire = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:54
 Embed = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:735
 CheckInstance = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:456
 ClearTimerData = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:568
 SetObjectFadeDurationIn = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:594
 ValidateTimerData = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:581
 CheckPossess = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:424
 UnregisterObjectFade = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:243
 UnregisterMessage = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\message.lua:299
 data = <table> {
 }
 GetCurrentFaderState = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:227
 CheckFocus = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\fader.lua:440
 DisableInstanceFading = <function> defined @Interface\AddOns\AzeriteUI
