### ISSUE TITLE
[Wrath] threat coloring on nameplates do not work in raids, or ever

### ISSUE THREAD

**Issue by Goldpaw** [GoldpawsStuff/AzeriteUI#160]

**Comment by nyrdh** [comment]
Tested this within a Dungeon Group with the Shaman tanking one mob an the bear the other:


![Image](https://user-images.githubusercontent.com/110252326/190362823-bb5bd9ef-b5d8-400c-a7b6-34bbf115a0ac.png)

And also didn't work within a Raid environment

**Comment by Goldpaw** [comment]
Nameplates and bars are threat colored in Wrath starting with version 3.2.561-RC.
