### ISSUE TITLE
In-game calendar apparantly can not be opened in Wotlk Classic

### ISSUE THREAD

**Issue by Kosmostic** [GoldpawsStuff/AzeriteUI#164]
**What WoW version do you wish to see this feature in?**
- [ ] Wrath of the Lich King Classic

**Is your feature request related to a problem? Please describe.**
It looks like the in-game calendar can't be opened in Azerite UI for Classic.

**Describe the solution you'd like**
A way to open the in-game calendar. 

**Describe alternatives you've considered**
/calendar does not work, and I haven't found any other addon that would make it so that the calendar button is displayed on the minimap, even when using Azerite UI.

**Additional context**
I also asked in the Goldpaw's Stuff Discord to make sure I wasn't missing something but looks like it's not working for Wotlk

![image](https://user-images.githubusercontent.com/108935980/191178864-fc329294-f752-401a-8377-6720ac3ed2b4.png)

**Comment by Goldpaw** [comment]
Added both the command and the mouse click to 3.2.560-RC, which should be out in a few hours!
