### ISSUE TITLE
Dragonflight errors

### ISSUE THREAD

**Issue by Antunes43** [GoldpawsStuff/AzeriteUI#167]
## The problem
Addon not working properly throws a bunch of errors on startup

### Did you update to the most recent version?
- [x] I have the latest addon version available from CurseForge or Wago.

### What game version(s) does it happen in? Choose your version and the highest expansion you own
- Live Realms
  - [ ] Classic Era / Vanilla
  - [ ] Burning Crusade Classic
  - [ ] Shadowlands (Retail)
- Public Test Realm
  - [ ] Classic Era / Vanilla
  - [ ] Burning Crusade Classic
  - [ ] Wrath of the Lich King
  - [ ] Shadowlands (Retail)
- Alpha/Beta
  - [ ] Wrath of the Lich King
  - [x] Dragonflight

### What addon theme(s) does it happen in?

- [x] Azerite
- [ ] Legacy
- [ ] I don't know what this means.

### Does this happen with ONLY this addon enabled?

- [x] Yes
- [ ] No

### Does this happen with absolutely all addons (this included) disabled?

- [ ] Yes
- [x] No

### What classes does it happen on?

- [ ] Death Knight
- [ ] Demon Hunter
- [ ] Druid
- [x] Evoker
- [ ] Hunter
- [ ] Mage
- [ ] Monk
- [x] Paladin
- [ ] Priest
- [ ] Rogue
- [ ] Shaman
- [ ] Warlock
- [ ] Warrior

### Any logs, screenshots, error output, etc?
Message: .../front-end/modules/blizzard/blizzard-chatwindows.lua:559: attempt to index local 'tabText' (a nil value)
Time: Thu Sep 22 22:44:41 2022
Count: 1
Stack: .../front-end/modules/blizzard/blizzard-chatwindows.lua:559: attempt to index local 'tabText' (a nil value)
[string "@Interface/AddOns/AzeriteUI/front-end/modules/blizzard/blizzard-chatwindows.lua"]:559: in function `postCreateWindow'
[string "@Interface/AddOns/AzeriteUI/back-end/libraries/chatframe.lua"]:89: in function `method'
[string "@Interface/AddOns/AzeriteUI/back-end/libraries/chatframe.lua"]:545: in function `ForAllEmbeds'
[string "@Interface/AddOns/AzeriteUI/back-end/libraries/chatframe.lua"]:115: in function `HandleWindow'
[string "@Interface/AddOns/AzeriteUI/back-end/libraries/chatframe.lua"]:122: in function `HandleAllChatWindows'
[string "@Interface/AddOns/AzeriteUI/front-end/modules/blizzard/blizzard-chatwindows.lua"]:872: in function `SetUpMainFrames'
[string "@Interface/AddOns/AzeriteUI/front-end/modules/blizzard/blizzard-chatwindows.lua"]:1056: in function `OnInit'
[string "@Interface/AddOns/AzeriteUI/back-end/libraries/module.lua"]:238: in function `Init'
[string "@Interface/AddOns/AzeriteUI/back-end/libraries/module.lua"]:268: in function `?'
[string "@Interface/AddOns/AzeriteUI/back-end/libraries/module.lua"]:737: in function `ForAll'
[string "@Interface/AddOns/AzeriteUI/back-end/libraries/module.lua"]:252: in function `Init'
[string "@Interface/AddOns/AzeriteUI/back-end/libraries/module.lua"]:867: in function `?'
[string "@Interface/AddOns/AzeriteUI/back-end/libraries/message.lua"]:65: in function `Fire'
[string "@Interface/AddOns/AzeriteUI/back-end/libraries/event.lua"]:71: in function <...erface/AddOns/AzeriteUI/back-end/libraries/event.lua:68>

Locals: self = <table> {
 GetChatWindowScrollBar = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/chatframe.lua:385
 GetChatWindowTabTextures = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/chatframe.lua:300
 modules = <table> {
 }
 ParseSavedVariables = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/db.lua:74
 SetChatWindowAsSlaveTo = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/chatframe.lua:155
 SetObjectFadeOverride = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/fader.lua:261
 SetAspectRatio = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/frame.lua:431
 SetHook = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/hook.lua:68
 layout = <table> {
 }
 NewConfig = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/db.lua:138
 GetChatWindowClickAnywhereButton = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/chatframe.lua:337
 SetSecureHook = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/securehook.lua:118
 GetFrame = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/frame.lua:405
 IsEnabled = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/module.lua:764
 PostCreateTemporaryChatWindow = <function> defined @Interface/AddOns/AzeriteUI/front-end/modules/blizzard/blizzard-chatwindows.lua:478
 GetChatWindowVoiceDeafenButton = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/chatframe.lua:325
 RegisterMessage = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/message.lua:276
 UnregisterMessage = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/message.lua:299
 GetAllChatWindows = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/chatframe.lua:94
 GetChatWindowScrollToBottomButton = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/chatframe.lua:377
 db = <table> {
 }
 RegisterUnitEvent = <function> defined @Interface/AddOns/AzeriteUI/back-end/libraries/message.lua:106
 SetUpMainFrames = <function> defined @Interface/AddOns/AzeriteUI/front-end/modules/blizzard/blizzard-chatwindows.lua:856
 GetConfig = <functi

### Steps to reproduce
just log in the game

### Expected behaviour
not pop the error

**Comment by Goldpaw** [comment]
Well there is no 10.0.0 compatible version of AzeriteUI yet, so this is to be expected. You're trying to put the square peg in a round hole! 

I mean, yes, I got it working, or at least starting, a few weeks back, but Dragonflight and its addon API is in development, they change things all the time. My priority right now is not Dragonflight, it's Wrath. Meaning this is a bug rapport about incompatibility with a product I haven't tried to make compatible yet. 

I'll start working on Dragonflight compatibility in October.

Closing this!
