### ISSUE TITLE
Bug after latest update :

### ISSUE THREAD

**Issue by fathermarss** [GoldpawsStuff/AzeriteUI#168]
## The problem
LUA error pop up during combat mostly, specifically clicking on enemy nameplates and during general combat.

### Did you update to the most recent version?
YES

### What game version(s) does it happen in? Choose your version and the highest expansion you own
WOTLK Live 3.4.0

### What addon theme(s) does it happen in?
LEGACY

### Does this happen with ONLY this addon enabled?
YES
### Does this happen with absolutely all addons (this included) disabled?
NO

### What classes does it happen on?
DEATH KNIGHT
### Any logs, screenshots, error output, etc?

POP UP ON ENEMY NAMEPLATE CLICK:

Message: ...ddOns\AzeriteUI\back-end\plugins\unit_classpower.lua:532: attempt to perform arithmetic on global 'r' (a nil value)
Time: Tue Sep 27 18:43:24 2022
Count: 1
Stack: ...ddOns\AzeriteUI\back-end\plugins\unit_classpower.lua:532: attempt to perform arithmetic on global 'r' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\AzeriteUI\back-end\plugins\unit_classpower.lua"]:532: in function `updateColor'
[string "@Interface\AddOns\AzeriteUI\back-end\plugins\unit_classpower.lua"]:1133: in function <...ddOns\AzeriteUI\back-end\plugins\unit_classpower.lua:1110>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\widgetcontainer.lua"]:205: in function <...Ons\AzeriteUI\back-end\libraries\widgetcontainer.lua:197>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

--------BREAK-------------
ADDITIONAL POP UP ON LOG IN:

Message: ...ddOns\AzeriteUI\back-end\plugins\unit_classpower.lua:551: attempt to perform arithmetic on global 'r' (a nil value)
Time: Tue Sep 27 18:47:04 2022
Count: 1
Stack: ...ddOns\AzeriteUI\back-end\plugins\unit_classpower.lua:551: attempt to perform arithmetic on global 'r' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\AzeriteUI\back-end\plugins\unit_classpower.lua"]:551: in function `updateColor'
[string "@Interface\AddOns\AzeriteUI\back-end\plugins\unit_classpower.lua"]:1133: in function <...ddOns\AzeriteUI\back-end\plugins\unit_classpower.lua:1110>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\widgetcontainer.lua"]:349: in function <...Ons\AzeriteUI\back-end\libraries\widgetcontainer.lua:338>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\widgetcontainer.lua"]:541: in function <...Ons\AzeriteUI\back-end\libraries\widgetcontainer.lua:541>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\SecureStateDriver.lua"]:100: in function <Interface\FrameXML\SecureStateDriver.lua:95>
[string "@Interface\FrameXML\SecureStateDriver.lua"]:127: in function <Interface\FrameXML\SecureStateDriver.lua:119>

Locals: 

Locals: 
### Steps to reproduce
Perhaps related to Death Knight and the newly added rune system, also I only use legacy. Click on an enemy nameplate. 

### Actual behaviour
Lua error pop up

**Comment by Goldpaw** [comment]
Yeah, I can even spot the problem in the code. Megaweird I never got any errors when testing it before upload. :o

Will have a fix ready shortly!

**Comment by Goldpaw** [comment]
Fixed in 3.2.566-RC.
