### ISSUE TITLE
Vehicle bar artwork shown when Bartender4 is enabled

### ISSUE THREAD

**Issue by Fernando-Marquardt** [GoldpawsStuff/AzeriteUI#170]
## The problem

I have recently installed AzeriteUI and have Bartender4 enabled aswell, the Vehicle bar is disabled in Bartender, but when I enter any vehicle, the default artwork is shown. This happens with the Bartender vehicle bar enabled and disabled, does not change anything.

This does not happen when only one of the addons is enabled alone.

### Did you update to the most recent version?
- [X] I have the latest addon version available from CurseForge or Wago.

### What game version(s) does it happen in? Choose your version and the highest expansion you own

- Live Realms
  - [ ] Classic Era / Vanilla
  - [ ] Burning Crusade Classic
  - [ ] Shadowlands (Retail)
- Public Test Realm
  - [ ] Classic Era / Vanilla
  - [ ] Burning Crusade Classic
  - [ ] Wrath of the Lich King
  - [ ] Shadowlands (Retail)
- Alpha/Beta
  - [X] Wrath of the Lich King
  - [ ] Dragonflight

### What addon theme(s) does it happen in?

- [X] Azerite
- [ ] Legacy
- [ ] I don't know what this means.

### Does this happen with ONLY this addon enabled?

- [ ] Yes
- [X] No

### Does this happen with absolutely all addons (this included) disabled?

- [ ] Yes
- [X] No

### What classes does it happen on?

- [ ] Death Knight
- [ ] Demon Hunter
- [ ] Druid
- [ ] Evoker
- [ ] Hunter
- [ ] Mage
- [ ] Monk
- [ ] Paladin
- [ ] Priest
- [ ] Rogue
- [ ] Shaman
- [X] Warlock
- [ ] Warrior

### Any logs, screenshots, error output, etc?

![image](https://user-images.githubusercontent.com/901883/194744951-bf7a6f2b-c8df-400e-bd03-5ea9b1d82e70.png)

### Steps to reproduce

Enable both AzeriteUI and Bartender4, and enter any vehicle.

### Expected behaviour

Only show the vehicle skills below the healthbar.

### Actual behaviour

It shows the vehicle skills as expected, but shows the default vehicle artwork as well (without any buttons inside).

**Comment by Goldpaw** [comment]
Not a bug in azeriteui, this is a bartender setting working as intended. And you can change it.

Open bartender options, disabled "use blizzard vehicle interface" (or something similar). It's on the front page of their settings, I think.

**Comment by Fernando-Marquardt** [comment]
I may have forgotten to mention in the issue, but the vehicle bar is disabled in the Bartender.
