### ISSUE TITLE
All Issues disappered in Mythic+. :(

### ISSUE THREAD

**Issue by Pregania** [GoldpawsStuff/AzeriteUI#18]
**What WoW version do you wish to see this feature in?**
- [x] Battle for Azeroth

**Is your feature request related to a problem? Please describe.**
In Mythic+ mode, all modules are uncallable, even including mini-maps and buff monitoring. In particular, the absence of target boxes caused unexpected problems in some situations.

**Describe the solution you'd like**
Hopefully, the lower right control menu will still be retained in Mythic mode, allowing users to make their own selections in Mythic, it's really important.

**Describe alternatives you've considered**
Or at least all the boxes will still exist in an invisible form.

**Comment by Pregania** [comment]
Hi! I sincerely hope that you will revise it. I've even replicated the player and target boxes with Weakauras (just to get into Mythic+) to make sure to use it all the time. But it's really unstable, and I still look forward to you seeing it and modifying it. :D

**Comment by ParadoxGery** [comment]
Hi, I like the UI but in Mythic+ all UI elements dissapear
The only other addon activating in m+ is Mythic Plus Timer however there are no error messages displayed

**Comment by goldpaw** [comment]
Smells like google translate. 

Anyhow, whatever bug this was, could never be replicated, and hasn't gotten any other reports. Closing it.
