### ISSUE TITLE
Target of target does not appear if the target is the player

### ISSUE THREAD

**Issue by P154** [GoldpawsStuff/AzeriteUI#19]
Easy to replicate - target of target appears to be visible unless the target is targeting the player. Unaware whether that's done on purpose or not.

**Comment by Goldpaw** [comment]
not a bug, it's a feature. 

we don't show the tot frame when the target is the player or the player's pet. Instead we use a red or blue or green eye next to the target frame portrait to indicate this. 

red eye = enemy targeting you
blue eye = enemey targeting your pet 
green eye = friendly targeting you

**Comment by P154** [comment]
That's actually awesome. Was wondering what were the eyes. Thanks!
