### ISSUE TITLE
Objective/Quest tracker only displaying up to 2 quests maximum.

### ISSUE THREAD

**Issue by AustinWalko** [GoldpawsStuff/AzeriteUI#20]
I'd like to start of by saying that I love this add on and it's the only add on I'd consider using for my UI. With that being said, no matter what I do I can only get up to 2 quests to show on the tracker at a time. If I disable the add on, the issue goes away. I'm trying to understand if it's intentional or not and if there is anyway that could be adjusted. I've looked through the add on files and found the objectviestracker in the front end, but wasn't able to find anything in there to help myself out. Any response would be appreciated.

Thanks and have a great day.

**Comment by goldpaw** [comment]
This was a bug related to how the addon sized the quest tracker, and had to do with the ui scaling setting in the graphic options.

This has since been fixed, and the full available space are now used for the tracker, in all themes. So this is solved in all recent versions. :)
