### ISSUE TITLE
Action bars don't move with bottom left frame

### ISSUE THREAD

**Issue by rebbo-cop** [GoldpawsStuff/AzeriteUI#20]
After unlocking frames and moving the three Bottom Left frames towards the center of the screen (to readjust for ultrawide resolutions) the action bars do not move.

![image](https://user-images.githubusercontent.com/70466329/206820633-7721e982-9d20-4aa8-82bf-94cc1851d65f.png)
![image](https://user-images.githubusercontent.com/70466329/206820599-2e3ccba5-5c66-42e6-ba29-ff3e01d84bd6.png)

This is in WOTLK Classic using [4.0.21-Release] 2022-12-09

**Comment by Goldpaw** [comment]
actionbars aren't movable, and won't be. their layout just isn't something that's very compatible with that. for movable bars, disable the bar (are some hints on how to do that on our discord), and use bartender.

**Comment by rebbo-cop** [comment]
Ah I see. A shame, as I found the Aspect Ratio quick adjustment setting in v3 to be incredibly useful since I have an ultrawide monitor.

**Comment by Goldpaw** [comment]
Wouldn't have worked in retail anymore, that aspect ratio thing. Can hardly move any blizzard frames at all now without breaking the editmode and with it the game. 

AzeriteUI5 is in the works and more or less ready within a week. That one will have the editmode fully intact, all our own frames movable, and several layout options for the bars as well as having the bars movable. 

And AzeriteUI4, this version, will be reworked to also have everything movable and layout choices, but for wrath only. Going to make a complete split between the code for the two wow versions now. They have become too different.
