### ISSUE TITLE
Problem with buff not showing on some characters

### ISSUE THREAD

**Issue by Xeltes** [GoldpawsStuff/AzeriteUI#23]
## The problem  
Hey there, for some reason none the Buff on top of the Health bar are not showing any more (Flask, food buffs, skills), I haven't changed any settings since i log out last night and when I started playing this morning they where not showing anymore

### Make sure you can check all these boxes  

- [Yes ] I have the latest addon version available from CurseForge/Overwolf/Twitch.
- [Yes] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### What addon release version(s) does it happen in?  
- If you have manually chosen a release type in the Twitch client, please tell me which one:
	- [ ] Alpha
	- [ ] Beta
	- [Yes ] Release (CurseForge/Twitch default)

### What game version(s) does it happen in?  

- [ ] Classic 
- [ ] Classic (Public Test Realm) 
- [Yes ] Battle for Azeroth 
- [ ] Battle for Azeroth (Public Test Realm) 

### Does this happen with NO other addons enabled?  

- Yes 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [Yes ] Druid 
- [Yes ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [Yes ] Warrior 

### Any logs, screenshots, error output, etc?  

No buffs showing (I had just used a flask and a feast)
 https://imgur.com/a/iGJjFoB
---
This Image of my Rogue and you can see the buffs are showing on my self and a random player
https://imgur.com/w1b19Sa

**Comment by joshbowman** [comment]
I'm seeing this same behavior for hunters/mages.  I do see some debuffs (e.g. brewfest eating contest "full" debuff), but nothing else out of combat.  Buffs display fine for other characters (lock/dh/dk/rogue).  Very annoying bug.  

Let me know if you need any additional info for debugging.  I opened debug console, hoping it would display some sort of error that might help, but there was nothing.

**Comment by goldpaw** [comment]
Not a bug. On druids, hunters, warriors and mages you have a menu option from the cogwheel menu called "aura filters". If you wish to go back to the time based default filters in azeriteui, you can choose "slack" from that menu. 

Other classes always default to slack filters as they haven't gotten their custom aura lists finished yet. 

My apologies for not replying to this sooner, btw. Somehow it slipped past me. It wasn't a bug when it was posted neither, though, and everything I just said applied 23 days ago too. :o

**Comment by joshbowman** [comment]
Thanks for the update.  I'd looked through the options in depth on my main, but somehow missed the extra aura option on the "bugged" alt.  Good stuff!
