### ISSUE TITLE
Aspect Ratio Reset

### ISSUE THREAD

**Issue by ZurielRedux** [GoldpawsStuff/AzeriteUI#24]
## The problem  
On a 21:9 Monitor, I like to have the map closer to the center of my screen, so I set the aspect Ratio to Widescreen (16:9). this change is remembered, but not respected if I restart the game, I have to manually set it to another option and back to widescreen every time I start the game again. not a huge deal, but a bug.

### Make sure you can check all these boxes  
- [X] I have the latest addon version available from CurseForge/Overwolf/Twitch.
- [X] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### What addon release version(s) does it happen in?  
- If you have manually chosen a release type in the Twitch client, please tell me which one:
	- [ ] Alpha
	- [ ] Beta
	- [ X ] Release (CurseForge/Twitch default)

### What game version(s) does it happen in?  

- [ ] Classic 
- [ ] Classic (Public Test Realm) 
- [ X ] Battle for Azeroth 
- [ ] Battle for Azeroth (Public Test Realm) 

### Does this happen with NO other addons enabled?  

- [ X ] Yes 
- [ ] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ X ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ X ] Warrior

**Comment by goldpaw** [comment]
Yeah, the call to set the aspect on startup got unintentionally blocked for a few builds here. Fixed in 2.1.401-RC, which should be available any second, if not already. :)
