### ISSUE TITLE
More settings for the addon

### ISSUE THREAD

**Issue by HectorZaGa** [GoldpawsStuff/AzeriteUI#25]
**What WoW version do you wish to see this feature in?**
- [ ] Battle for Azeroth

**Is your feature request related to a problem? Please describe.**
To be honest I love this UI proposal, but I would make some changes and add a few more things. I feel that it is a bit uncomfortable that the minimap is located in the lower right corner, also that the button on the backpack is the option button. Another thing that I do not get used to is that the action and life bar of the character is hidden. I also feel that the interface is very large

**Describe the solution you'd like**
I think a solution would be to increase the options of the addon, such as changing the place of the minimap, separating the game panel and the backpack into two buttons. Also that the addon configuration is inside "interface" like all addons. Also have the option to change the location of the target's health bar. And also that the number of buttons in the action bar be the same as WoW offers you. Increase one more option to prevent your action and life bar from being hidden and be able to adjust the size of the HUD.

**Comment by goldpaw** [comment]
No. All of this has been answered at length in the addon description.
