### ISSUE TITLE
Lack of some important resource bar

### ISSUE THREAD

**Issue by RockghostWoW** [GoldpawsStuff/AzeriteUI#26]
**What WoW version do you wish to see this feature in?**

- [x] Battle for Azeroth

**Is your feature request related to a problem? Please describe.**

Hi, I just foud your UI while i was working on a setup for ConsolePort and, man, it's just amazing. The problem is that for some classes there's no specific resource bar that are vital for that class (like Holy Power for paladins and Chi Point/Stagger for monks). I really would like a lot to play those classes with your UI but is really difficult to do if i can't see a core gameplay mechanics.

**Describe the solution you'd like**

Just implement the missig resource bar, this would help a lot for clarity.

**Describe alternatives you've considered**

 I don't think there's really an alternative, maybe add some "volatile bar" over a character head but it would be too much out of context.

**Comment by goldpaw** [comment]
AzeriteUI shows chi, stagger, holy power, arcane charges, soul fragments, soul shards, combo points and runes. It's shown in the center of the screen, to the left of your character. 

The majority of them are only visible when you have something targeted, though. This is intended, but definitely something I can adjust. I'll look into making this system a bit better for the player, so you're not left wondering what number of resources you have, or forced to target something to figure it out. :+1: 

So no missing resources here, but probably some that might could stand to be a little more visible? :)

**Comment by RockghostWoW** [comment]
Ah, ok, I tested better now and i found one of my addon was the cause of the problem. Sorry.

After the test i can say that this system works vey good with generated point resources like Holy Power, Chi Point and so on. For stagger and runes there's a lack of clarity in my opinion: stagger dosen't really tell you how much damage you have staggered (maybe a bar would work better than a dot interface) and for runes i found myself to find counter-intuitive to have to target someone to see how much time is left for the recharge even if i don't whant to engage a fight.

Maybe the best solution would be to have an option to toggle a secondary resource bar over/under the health bar (like the pet one)? So one can choose wich one works the better for his playstyle?

Still i find it's crazy good how your UI and ConsolePort work together. Have you ever think to work with them to create a addon/mod-pack for a definitive full-immersion experience?

**Comment by goldpaw** [comment]
Runes should be there at all times, just more transparent when not targeting anything. That's the intention, at least. But as I said, definitely room for some tweaking and improvements here. If the amount of toning down going on when not targeting or engaged in combat is causing the gameplay to be harder, then I'll tweak that to something more visible. 

The whole mission statement of the ui is to only show what we need, when we need it. That doesn't mean that we're super authorities on what and when, though. I usually give classes and overhaul when I get around to leveling them to 120, and so far that has only happened with a feral druid, warrior and a hunter. Which I think the UI reflects, lol! :rofl: 

Will work in some changes to rune visibility (and the other resources for that matter), and update this thread when done. :+1: 

And yeah, I thought about making something specifically for consoleport, but ultimately chose not to. Just not enough time in day to fit everything in! I might revisit the idea in Shadowlands, though. From what I hear WoW is getting generic keybind support for gamepads there, making addons like ConsolePort work almost without wowmapper or whatever tool people are using to translate gamepad input to keyboard input. This won't replace anything ConsolePort does, just make it easier for it, really. 

Time will tell! I might create something that fits ConsolePort like a glove, I might not. ;)

**Comment by RockghostWoW** [comment]
Ok, for the Brewmaster monk i could say that you nailed the "when" but it's not the best "what", lol!  🤣

The circle interface is not the best (obviously IMO), a curved-shaped bar in the same position that continuosly refill would be so much more clear for better maximise the purifing timing and efficiency.

As it is now, i can say that with a minimum tweaking it's already a perfect fit for ConsolePort. I streamed a pair of live with your UI setupped in combination with CP and the viewers were speechless. 👍
