### ISSUE TITLE
Interface keeps disappearing

### ISSUE THREAD

**Issue by Firvenn** [GoldpawsStuff/AzeriteUI#28]
## The problem  
The whole interface keeps disappearing even though I chose the "always display" option for both main bars and pet's interface as well (the name of the option may be different actually, since I play russian version, but I think it's clear that I want the interface and binded slots to be displayed all the time). <br>I tried turning off all other addons, restarting the game, reloading the interface - with no result. The interface (except for the map) starts acting as if the option of display on hover is chosen after I mount or pick up a fight.

### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge/Overwolf/Twitch.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### What addon release version(s) does it happen in?  
- If you have manually chosen a release type in the Twitch client, please tell me which one:
	- [ ] Alpha
	- [ ] Beta
	- [x] Release (CurseForge/Twitch default)

### What game version(s) does it happen in?  

- [ ] Classic 
- [ ] Classic (Public Test Realm) 
- [x] Battle for Azeroth 
- [ ] Battle for Azeroth (Public Test Realm) 

### Does this happen with NO other addons enabled?  

- [x] Yes 
- [ ] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [x] Warlock 
- [ ] Warrior

**Comment by goldpaw** [comment]
You're only changing actionbar visibility. The option that handles the fading of the player frame and the rest is called "Explorer Mode" (in English) and is available in the top level of the menu.

**Comment by Firvenn** [comment]
Oh, I see! Thank you very much!
