### ISSUE TITLE
Better indication of what nameplate currently is selected.

### ISSUE THREAD

**Issue by Saekyz** [GoldpawsStuff/AzeriteUI#30]
**What WoW version do you wish to see this feature in?**
- [X] Classic
- [X] Battle for Azeroth

**Is your feature request related to a problem? Please describe.**
Difficulty in being able to identify the target's nameplate when there are several enemies together as it is not very noticeable the difference between when the target is selected and when not.

**Describe the solution you'd like**
My suggestion would be to add some icon to identify the current target, increase the glow of the nameplate or add a different nameplate color for selected target and nearby enemies.

**Describe alternatives you've considered**
So far no alternative as it uses AzeriteUI without any modifications

**Additional context**

**Comment by goldpaw** [comment]
Since this report, the selected nameplate has gotten both larger and have it's name and health text visible, contrary to the other plates. So that should do the trick.

**Comment by goldpaw** [comment]
Going to re-open this again, as I my recent changes sometimes simply aren't enough. I'm planning a system to change the level of highlight / size changes depending on how many other nameplates currently are visible. Might even add an outline to further indicate it. 

I'll update this issue when I have something to share! :)

**Comment by goldpaw** [comment]
Closing this, but it's totally been added. Nameplates have both target and focus outlines now. :)
