### ISSUE TITLE
Auto-hide the minimap or Pin the minimap

### ISSUE THREAD

**Issue by WallBlaster** [GoldpawsStuff/AzeriteUI#31]
**What WoW version do you wish to see this feature in?**
-Battle for Azeroth

**Is your feature request related to a problem? Please describe.**
I remember playing Dark Souls, the UI will auto hide itself, makes the game really immersive. 
AzeriteUI is great but if only the there is an option to turn on auto hide the minimap and the rest of the things, turning the visual completely UI-less without constantly hitting Alt+Z would be awesome!

**Describe the solution you'd like**
An auto-hide everything after set amount of seconds. Mouseover the minimap and it would appear.

**Describe alternatives you've considered**
Or just auto-hide the minimap after set amount of seconds. Adding a 'Pin' key to lock the minimap so it no longer auto-hide with just a click.

**Additional context**
This would be great for Streaming or showcasing the shear immersion of wow.

Thanks very much love your work, please consider the feature suggestion~

**Comment by loicpetit** [comment]
Hi. I discovered that wonderful addon and I would like too an option to hide the minimap and buttons around in exploratory mode in order to have completly no UI at all without mouse over it. 
I actually search full immersion and that addon just miss that :) 
Keep the great work !

**Comment by goldpaw** [comment]
Not fully possible. The whole minimap doesn't follow normal alpha changes, so it's an either/or thing to show it. Fading it in and out is NOT an alternative that will work. For example it won't affect the icons within the minimap, just the backdrop in it. 

Also, many things connected to the minimap are often secure elements that can't be toggled while in combat. So auto-hiding is a really risky thing to do. 

You don't have to alt+z to hide it, though, you can assign a keybind to toggle the minimap in blizzard's keybind menu under the interface panels sub-section. That's what I do.

**Comment by loicpetit** [comment]
thanks for the tip I will look at it :)
