### ISSUE TITLE
corruption disappearing when talented into absolute corruption

### ISSUE THREAD

**Issue by afflock** [GoldpawsStuff/AzeriteUI#33]
Corruption not staying on targets once other dots have applied and also when its the only dot on them it does not show

**Comment by afflock** [comment]
Just did a test, when the warlock has the https://www.wowhead.com/spell=196103/absolute-corruption
it seems to not show the dot, but take it off and it shows.

**Comment by afflock** [comment]
****FIXED****  FULL CREDIT FOR THIS FIX GOES TO "Nameless" in the discord.

This is intended for noobs like me to fix this.


So first the actual issue. 
This seems to be a while list issue and seems to be by design (CN) 
Problem: When talented, absolute corruption will disappear from the target nameplate.
Solution: 
Step 1: download VSC so we can modify a document (its easy don't be scared) 
Step 2: find your way to you this folder, its usually~ D:\World of Warcraft\_retail_\Interface\AddOns\AzeriteUI\back-end\tools 
Step 3: open the auras file with VSC
Step 4: navigate to the line right after line 1104 below the Hunter section and before  "end" (yes its the hunters section but its still gunna work so just roll with it)
Step 5: copy paste this into that line
**AddUserFlags(146739, ByPlayer)                 -- Corruption 1
AddUserFlags(317031, ByPlayer)                 -- Corruption 2
AddUserFlags(334342, ByPlayer)                 -- Corruption 3
AddUserFlags(196103, ByPlayer)                 -- Corruption talent**
Step 6: reload by typing /rl in chat and you should be good to go!!

You have now fixed the issue.

Credit again goes to nameless.

**Comment by goldpaw** [comment]
Haven't gotten around to doing the full warlock lists yet, as Nameless discovered, but I'll put these into the baseline version, if nothing else. Will be included in the next updated!

**Comment by goldpaw** [comment]
On a sidenote, only 146739 and 317031 are auras, the others are spells, and aren't relevant for the list. The filters go by the spellID of auras that appear on units, not by the spellIDs of the spells that cast them.
