### ISSUE TITLE
Better ultrawide positioning

### ISSUE THREAD

**Issue by wolmeister** [GoldpawsStuff/AzeriteUI#34]
**What WoW version do you wish to see this feature in?**
- [ ] Classic
- [x] Battle for Azeroth

**Is your feature request related to a problem? Please describe.**
When using an ultrawide resolution, the UI remains in the same position as in a normal resolution, not sticking to the corners.

**Describe the solution you'd like**
The UI should always be in the corner of the screen, independent of the resolution.

**Screenshots**
Ultrawide:
https://i.imgur.com/PwLO6vV.jpeg

Wide:
https://i.imgur.com/TSDrsQu.jpg

**Comment by goldpaw** [comment]
Setting already exists. Cogwheel menu in the bottomright corner > aspect ratio. You can truncate the UI to 16:9, 21:9, or use the full width regardless of how supermegawide it is.

**Comment by ericschmar** [comment]
I understand that the original issue was listed for retial, and also that this is now 1.5 years later, but where is the support for this feature in TBC classic?

I'm looking at the bottom right corner > aspect ratio, but there is no option called aspect ratio

**Comment by goldpaw** [comment]
Ah, yes. The middle-click problem! There's been eternal discussion about what buttons to have what menus on. The general opinion seems to be that anything is bad to have on the middle button!

I reckon that I'll have to improve the menu system to be easier to navigate at some point. But probably saving that for the next version.

**Comment by ericschmar** [comment]
It was definitely my fault. The mouse-over showing the click options was a good idea, and follows exactly what other add-on developers do. If anything, keeping that line of thinking, most other devs don't do middle click, instead they stick to left/right and modifiers like ctrl or shift. You could consider doing it like that. Or potentially add a menu option to the esc menu that brings up settings.
