### ISSUE TITLE
Hide all action buttons

### ISSUE THREAD

**Issue by zombiesgd** [GoldpawsStuff/AzeriteUI#35]
**What WoW version do you wish to see this feature in?**
- [ ] Classic
- [ x] Battle for Azeroth

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] no problems

**Describe the solution you'd like**
A clear and concise description of what you want to happen. I just want to be able to hide all action buttons since i play on consolport ui and you have made it posibble to hide almost all of the action buttons, why not all of them

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. You can list other addons you're using to achieve this here. Ive tryed puting the ui’s on tip of echother but it gets messy, 

**Additional context**
Add any other context or screenshots about the feature request here. Love this product and hope you are able to do this

**Comment by goldpaw** [comment]
https://github.com/GoldpawsStuff/AzeriteUI#how-can-i-disable-the-actionbars
