### ISSUE TITLE
Cast Bar - Hidden until disabled and re-enabled

### ISSUE THREAD

**Issue by Thrayde** [GoldpawsStuff/AzeriteUI#36]
## The problem  
Casting spells, using items with AzeriteUI addon enabled does not show the AzeriteUI cast bar. The Issue exists on all characters, even newly created ones with only AzeriteUI enabled. Disabling Cast Bar from AzeriteUI HUD menu and re-enabling it fixes the issue but the problem reappears when logging out and back into the same character or different character. Reloading the interface also causes the problem to occur.

### Make sure you can check all these boxes  

- [X] I have the latest addon version available from CurseForge/Overwolf/Twitch.
- [X] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### What addon release version(s) does it happen in?  
- If you have manually chosen a release type in the Twitch client, please tell me which one:
	- [ ] Alpha
	- [ ] Beta
	- [X] Release (CurseForge/Twitch default)

### What game version(s) does it happen in?  

- [ ] Classic 
- [ ] Classic (Public Test Realm) 
- [X] Battle for Azeroth 
- [ ] Battle for Azeroth (Public Test Realm) 

### Does this happen with NO other addons enabled?  

- [X] Yes 
- [ ] No 

### What classes does it happen on?  

- [X] Death Knight 
- [ ] Demon Hunter 
- [X] Druid 
- [X] Hunter 
- [X] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [X] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [X] Warrior 

### Any logs, screenshots, error output, etc?  
No LUA errors or errors of any other kind presented when the problem occurs.

### Steps to reproduce  
Enable AzeriteUI addon, log into a new or existing character, cast a spell, or use the hearthstone in the character's inventory.

### Expected behaviour  
AzeriteUI cast bar shows when casting a spell or using an item with a casting time/channeling time.

### Actual behaviour  
Player character cast animation shows (sometimes it doesn't) but the AzeriteUI cast bar is not displayed while casting.

**Comment by goldpaw** [comment]
Pretty certain you have personal resource display (player's nameplate) enabled in the blizzard interface settings under "names". Our centered castbar is disabled when the PRD is enabled, to avoid overlapping since they're basically in the same place. This is intended.

**Comment by Thrayde** [comment]
You are correct - I did have the personal resource display enabled in the interface settings. Disabling that setting does restore the cast bar. I had no idea this was intended/expected behavior. Apologies for taking up your time with this unnecessary report and I appreciate you taking the time to respond so quickly. (Love the addon, btw!)

**Comment by goldpaw** [comment]
Not a problem in the world! :) 

It doesn't always work perfectly as intended, though, as the blizzard PRD sometimes remain invisible when casting, and don't show up until combat actually begins. I'm considering making the system a bit "smarter", and have the castbar just visually fade in/out based on the PRD instead of actually being turned on/off. 

It's on my ToDo list!
