### ISSUE TITLE
Beast lore does not show up in creature tooltip

### ISSUE THREAD

**Issue by sage-afk** [GoldpawsStuff/AzeriteUI#37]
## The problem  
When casting the hunter spell [Beast Lore](https://wow.gamepedia.com/Beast_Lore), the creature's tooltip does not update with the new info as shown below under the screenshots section.

### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge/Overwolf/Twitch.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### What addon release version(s) does it happen in?  
- If you have manually chosen a release type in the Twitch client, please tell me which one:
	- [ ] Alpha
	- [ ] Beta
	- [x] Release (CurseForge/Twitch default)

### What game version(s) does it happen in?  

- [ ] Classic 
- [ ] Classic (Public Test Realm) 
- [x] Battle for Azeroth 
- [ ] Battle for Azeroth (Public Test Realm) 

### Does this happen with NO other addons enabled?  

- [x] Yes 
- [ ] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [x] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  

![image](https://user-images.githubusercontent.com/73270060/96825240-45458a80-13f6-11eb-8402-19be76305b42.png) ![image](https://user-images.githubusercontent.com/73270060/96825258-51c9e300-13f6-11eb-941d-8061359813b8.png)

### Steps to reproduce  

1. Cast Beast Lore on a creature, then check hover tooltip.

### Expected behaviour  

Additional info added to the creature's tooltip

### Actual behaviour  

No change occurs.

**Comment by goldpaw** [comment]
AzeriteUI lets most addon added info in the worldframe mouseover tooltips through now. We will not however add third party information to our own unitframe tooltips.
