### ISSUE TITLE
AzeriteUI not compatible with M6 addon

### ISSUE THREAD

**Issue by ZaViper** [GoldpawsStuff/AzeriteUI#38]
## The problem  

AzeriteUI will not show tool tips of macros created with the M6 addon. Macros created with M6 will display correctly in other action button addons like Dominos and Bartender, but not AzeriteUI

### Make sure you can check all these boxes  

- [ +] I have the latest addon version available from CurseForge/Overwolf/Twitch.
- [ +] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### What addon release version(s) does it happen in?  
- If you have manually chosen a release type in the Twitch client, please tell me which one:
	- [ +] Alpha
	- [ +] Beta
	- [ +] Release (CurseForge/Twitch default)
I have tried all three.

### What game version(s) does it happen in?  

- [ ] Classic 
- [ ] Classic (Public Test Realm) 
- [ +] Battle for Azeroth 
- [ ] Battle for Azeroth (Public Test Realm) 

### Does this happen with NO other addons enabled?  

- [ +] Yes 
- [ ] No 
I tried with just these two addons.

### What classes does it happen on?  

- [ +] Death Knight 
- [ +] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ +] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 
I don't have any other classes to test this on.

### Any logs, screenshots, error output, etc?  

https://imgur.com/a/q2l6XRV

### Steps to reproduce  

Just install M6, create a macro with it, then put the macro in one of AzeriteUI's action buttons.

### Expected behaviour  

AzeriteUI should display the tool tip of macro.

### Actual behaviour  

AzeriteUI doesn't display the tool tip of the macro. Just says something like "_M6+s02" or "_M6+s08" depending on the macro labeling.

**Comment by goldpaw** [comment]
AzeriteUI lets most addon added info in the worldframe mouseover tooltips through now. We will not however add third party information to our own unitframe tooltips.
