### ISSUE TITLE
Holy Power Not Displaying When Targeting Friendly

### ISSUE THREAD

**Issue by Duchaelor** [GoldpawsStuff/AzeriteUI#39]
## The problem  

When targeting an enemy on a Holy Paladin, my Holy Power displays normally. However, when targeting a friendly character, its alpha is 0. Since Holy Power is mostly generated through and used on healing for Holy, it'd be nice to have it visible.

### Make sure you can check all these boxes  

- [ X] I have the latest addon version available from CurseForge/Overwolf/Twitch.
- [ X] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### What addon release version(s) does it happen in?  
- If you have manually chosen a release type in the Twitch client, please tell me which one:
	- [ ] Alpha
	- [ ] Beta
	- [X ] Release (CurseForge/Twitch default)

### What game version(s) does it happen in?  

- [ ] Classic 
- [ ] Classic (Public Test Realm) 
- [ X] Battle for Azeroth 
- [ ] Battle for Azeroth (Public Test Realm) 

### Does this happen with NO other addons enabled?  

- [X ] Yes 
- [ ] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ X] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  

https://imgur.com/a/pNAJZCt

### Steps to reproduce  

Seems to happen any time you have holy power on Holy spec, and target a friendly target. Can also be reproduced on Ret and Prot (although those specs make a bit more sense to have the classpower hidden on while targeting a friendly). I've been able to see it in dungeons and open world thus far.

### Expected behaviour  

Holy Power should display with any target

### Actual behaviour  

Holy Power only displays with hostile target

**Comment by goldpaw** [comment]
Holy Power was made to be visible regardless of target in build 3.0.423-RC some weeks ago, so I'm closing this issue now. Better late than never.
