### ISSUE TITLE
being able to change the raid difficulty and dungeon difficulty

### ISSUE THREAD

**Issue by Angrygrandpa1** [GoldpawsStuff/AzeriteUI#41]
**What WoW version do you wish to see this feature in?**
- [ ] Classic
- [ ] Battle for Azeroth

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. You can list other addons you're using to achieve this here.

**Additional context**

**Comment by goldpaw** [comment]
Just right-click your unitframe, it's in the regular drop-down there.

**Comment by Angrygrandpa1** [comment]
I have it just brings up settings for the add on ui

**Comment by goldpaw** [comment]
No. Unit frame. The big red player health bar in the bottom left corner. Right-click it. It's there.

**Comment by Angrygrandpa1** [comment]
oh ok cool thank you so much
