### ISSUE TITLE
Having an option that control character casting error feedback

### ISSUE THREAD

**Issue by MEndermanM** [GoldpawsStuff/AzeriteUI#42]
_**What WoW version do you wish to see this feature in?**_
- [ ] Classic
- [x] Battle for Azeroth

_**Is your feature request related to a problem? Please describe.**_

I'm a character voice's lover, I enjoyed listening to every races's error feedback voice.
That was a little sad with _AzeriteUI_ disabled character feedback.
By the way, I have disabled all addons to test that actually _AzeriteUI_  do disable them.

_**Describe the solution you'd like.**_

One more option under `press to cast` is the easiest way to do.
Or you can just put it back! Because we have already a option with muting casting error feedback in sound system setting.

_**Describe alternatives you've considered.**_

I don't think there's a addon could restore the sound that have been muted.
If it does, please tell me and i will be appreciate.

**Comment by goldpaw** [comment]
Did a little digging, and figured out the origin of those sounds you're talking about lies in the blizzard UIErrorsFrame, the red error text on-screen. 

I'll add them back, but connect them to the error speech option in the audio settings panel, something blizzard did NOT do.

**Comment by goldpaw** [comment]
This was added several builds ago, I just forgot to close the issue.
