### ISSUE TITLE
More action bars/slots

### ISSUE THREAD

**Issue by Lemonlions** [GoldpawsStuff/AzeriteUI#43]
**What WoW version do you wish to see this feature in?**
- [X ] Classic
- [X ] Battle for Azeroth

**Is your feature request related to a problem? Please describe.**
At current there is only +17 action bars/slots and for classes with more options to pick and choose from (mage *cough*) there is not enough space

**Describe the solution you'd like**
A second lot of action bars/slots on that can be placed either side of the screen (left/right)

**Comment by goldpaw** [comment]
Already answered on the download pages of all places the UI can be downloaded:
https://github.com/GoldpawsStuff/AzeriteUI#how-can-i-get-more-action-buttons-and-where-is-the-stance-bar
