### ISSUE TITLE
Klikixx's Webspinner cannot be undone.

### ISSUE THREAD

**Issue by zysoring** [GoldpawsStuff/AzeriteUI#44]
## The problem  
 Some toys cannot be cancelled once used without disabling the addon and then clicking the Toy effect off.

### Make sure you can check all these boxes  

- [ y] I have the latest addon version available from CurseForge/Overwolf/Twitch.
- [y ] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### What addon release version(s) does it happen in?  
- If you have manually chosen a release type in the Twitch client, please tell me which one:
	- [ ] Alpha
	- [ ] Beta
	- [ y] Release (CurseForge/Twitch default)

### What game version(s) does it happen in?  

- [ ] Classic 
- [ ] Classic (Public Test Realm) 
- [ y] Battle for Azeroth 
- [ ] Battle for Azeroth (Public Test Realm) 

### Does this happen with NO other addons enabled?  

- [y ] Yes 
- [ ] No 

### What classes does it happen on?  

- [ y] Death Knight 
- [y ] Demon Hunter 
- [y ] Druid 
- [ y] Hunter 
- [ y] Mage 
- [ y] Monk 
- [y ] Paladin 
- [y ] Priest 
- [y ] Rogue 
- [y ] Shaman 
- [y ] Warlock 
- [y ] Warrior 

### Expected behaviour  

the buff simply isnt showing up on the buff bar or anywhere on the UI. thats all thats needed to fix it.

**Comment by goldpaw** [comment]
cogwheel menu > aura filter > spam

that should show it
