### ISSUE TITLE
NPC dialogue missing in chat history

### ISSUE THREAD

**Issue by Martinian1** [GoldpawsStuff/AzeriteUI#45]
## The problem  
NPC dialogue is missing in my chat history. As I switch this addon mainly for story and immersion, this is kind of immersion breaking as the dialogue bubbles are quickly gone so I can't re-read what has been said in the story. I have all creature messages switched on and it is missing still. 

### Make sure you can check all these boxes  
- [ ] I have the latest addon version available from CurseForge/Overwolf/Twitch.
- [ ] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### What addon release version(s) does it happen in?  
	- [ ] Release (CurseForge default)

### What game version(s) does it happen in?  
- [ ] Battle for Azeroth

### Does this happen with NO other addons enabled?  
- [ ] Yes 

### What classes does it happen on?  
- [ ] Paladin 

### Any logs, screenshots, error output, etc?  
![WoWScrnShot_111620_222635](https://user-images.githubusercontent.com/39560856/99310235-fe16b200-285a-11eb-9084-8bf32f1c7ec2.jpg)
![WoWScrnShot_111620_222704](https://user-images.githubusercontent.com/39560856/99310400-47ff9800-285b-11eb-913a-86097c530125.jpg)

### Steps to reproduce  
Go to Genn Greymane and stay awhile and listen. 

### Expected behaviour  
The dialogue should show up as a bubble above NPC and as a text in chat history aswell.

### Actual behaviour  
The dialogue shows only as a bubble above NPC

**Comment by goldpaw** [comment]
There are spam filter options in OUR menu that control where and how these are displayed, and you need to disable those for this to show up. 

So not a bug, fully intentional, and you can change the setting! :)

![WoWScrnShot_113020_174904](https://user-images.githubusercontent.com/6476535/100638557-750c7a00-3334-11eb-8a24-3e978e00f42b.jpg)
