### ISSUE TITLE
In-game issue with quest objective.

### ISSUE THREAD

**Issue by VikingCookie** [GoldpawsStuff/AzeriteUI#46]
## The problem  

Is the quest where you are gonna activate the Anima Conduits. you will get a new button to click on to be able to activate the anime conduits. when i am using the addon that button is gone and only shows up if i disable all addons. Fix pls..

### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge/Overwolf/Twitch.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### What addon release version(s) does it happen in?  
- If you have manually chosen a release type in the Twitch client, please tell me which one:
	- [ ] Alpha
	- [ ] Beta
	- [x] Release (CurseForge/Twitch default)

### What game version(s) does it happen in?  

- [ ] Classic 
- [ ] Classic (Public Test Realm) 
- [x] Battle for Azeroth 
- [ ] Battle for Azeroth (Public Test Realm) 

### Does this happen with NO other addons enabled?  

- [ ] Yes 
- [ ] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior

**Comment by goldpaw** [comment]
I have the definite feeling I just closed and answered an almost identical issue regarding the exact same thing. It's been dealt with.
