### ISSUE TITLE
Azerite UI blocking special quest action buttons

### ISSUE THREAD

**Issue by Bashadash** [GoldpawsStuff/AzeriteUI#47]
on the quests where (for example) you are gonna activate the Anima Conduits. you will get a new button to click on to be able to activate the anime conduits. when I am using the addon that button is gone and only shows up if I disable azeriteui.

**Comment by goldpaw** [comment]
I could be wrong, but I definitely believe this was either the ExtraActionButtons or the zone ability buttons which in Shadowlands can be both 2 and 3 at once. That should be fixed now, or at least everything is visible and clickable. :)

**Comment by Bashadash** [comment]
Thank you. It was because I was not dragging the steward button to my bars,
thus blocking the quest button.

I have another issue where i can not see progress bars on the quest for the
forge in Bastion. I think another addon is blocking, as my friend does not
have the problem, and if i disable azeriteui its fine.
