### ISSUE TITLE
Issues leaving certain vehicles in dungeons

### ISSUE THREAD

**Issue by Saitake** [GoldpawsStuff/AzeriteUI#48]
I have run into this issue a number of times and it seems a very consistant issue.
In dungeons, it will be impossible to leave certain vehicles/objects without disabling azerite UI.
Instead, when you click the leave button, the zone map will pop up instead.

I have consistently (100% of the time) encountered this on the cannon at the end of Siege of Boralas when fighting the squid.
I have commly encountered this on the cannons in Tol Dagor, although only started noticing it recently.

**Comment by goldpaw** [comment]
I've never encountered this at all. Ever. 

And the exit button we have placed on the minimap (in both UI themes) have absolutely no scripts attached to it to toggle any sort of map. 

I'm guessing this is a conflict of some sort, where some other addon is putting things on the minimap covering our exit button, or just attempting to take control of various minimap elements themselves. Either way, this report contains nothing except "there's a bug", and the template supplied seems to be missing from your report. So I have no info here.
