### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Bashadash** [GoldpawsStuff/AzeriteUI#53]
## The problem  
I get a lua script error when depositing anima in my covenant (kyrian).

### Make sure you can check all these boxes  

- [x ] I have the latest addon version available from CurseForge/Overwolf/Twitch.
- [ x] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What addon release version(s) does it happen in?  
- If you have manually chosen a release type in the Twitch client, please tell me which one:
	- [ ] Alpha
	- [ ] Beta
	- [x ] Release (CurseForge/Twitch default)

### What game version(s) does it happen in?  

- [ ] Classic 
- [ ] Classic (Public Test Realm) 
- [x ] Battle for Azeroth (shadowlands)
- [ ] Battle for Azeroth (Public Test Realm) 

### What addon theme(s) does it happen in?  

- [ x] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with NO other addons enabled?  

- [ ] Yes 
- [x ] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [x ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [x ] Shaman 
- [ ] Warlock 
- [ ] Warrior

**Comment by Bashadash** [comment]
[lua error 11.30.2020.txt](https://github.com/GoldpawsStuff/AzeriteUI/files/5620142/lua.error.11.30.2020.txt)

**Comment by Spherikal** [comment]
I get this error too, so you can add Demon Hunter to the affected list as well.

I belong to the Kyrian covenant if that helps!

**Comment by goldpaw** [comment]
This has been fixed a few days ago. Closing it! :)
