### ISSUE TITLE
LegacyUI bar settings reset, 'Cast On Down' always on

### ISSUE THREAD

**Issue by Sigmastorm7** [GoldpawsStuff/AzeriteUI#55]
## The problem  

The LegacyUI theme never remembers my actionbar settings, at least functionally, and 'Cast on Down' is always enabled no matter what. The button lock setting gets reset any time there is a manual reload (enabling LegacyUI, reloading, relogging). Loading screens when teleporting do not cause any issues. The button lock issue can be resolved by turning the setting on and then off again, but cast on down is permanently enabled. This issue only occurs with the Legacy theme and I've never encountered it with the Azerite theme.

### Make sure you can check all these boxes  

- [X] I have the latest addon version available from CurseForge.
- [X] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [X] Retail 
	- [X] Battle for Azeroth
	- [X] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [ ] Azerite 
- [X] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [X] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [ ] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [X] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [X] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [X] Warlock 
- [ ] Warrior 

### Steps to reproduce  

Enabling LegacyUI, reloading with LegacyUI enabled, or relogging with LegacyUI enabled cause the addon to reset the 'Button Lock' setting.

### Expected behaviour  

As with AzeriteUI, both 'Button Lock' and 'Cast on Down' settings, after being disabled once before, should remain disabled when switching to Legacy/relogging/reloading. 'Cast on Down' should disable properly.

### Actual behaviour  

The settings UI at least remembers which settings were changed, showing red 'Button Lock' and 'Cast on Down' buttons. All action bar buttons are locked until the setting is turned on and off again, while cast on down cannot be disabled at all.

**Comment by goldpaw** [comment]
Found and fixed this. Will be included in the next update. It will force a settings reset for all azerite theme actionbar settings, as the issue was that each theme used a different setting system and now both have been fully transitioned to the new system. This is a one-time settings reset, though, and will only apply to the actionbars. 

Will let this issue remain open until the fix is live on CurseForge.

**Comment by goldpaw** [comment]
Fixed in 3.1.439-RC, being processed and soon live on CurseForge now.
