### ISSUE TITLE
Bad Argument AP Bug

### ISSUE THREAD

**Issue by Capadillo** [GoldpawsStuff/AzeriteUI#57]
## The problem  

_I log in, with no other addons enabled and receive a Lua Error without doing anything._

### Make sure you can check all these boxes  

- [X] I have the latest addon version available from CurseForge.
- [X] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [X] Retail 
	- [ ] Battle for Azeroth
	- [X] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [X] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [X] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [X] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [X] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  

_Message: ...AzeriteUI\back-end\plugins\generic_artifactpower.lua:111: bad argument #1 to 'GetAzeriteItemXPInfo' (Usage: local xp, totalLevelXP = C_AzeriteItem.GetAzeriteItemXPInfo(azeriteItemLocation))
Time: Sun Dec  6 10:06:30 2020
Count: 2
Stack: ...AzeriteUI\back-end\plugins\generic_artifactpower.lua:111: bad argument #1 to 'GetAzeriteItemXPInfo' (Usage: local xp, totalLevelXP = C_AzeriteItem.GetAzeriteItemXPInfo(azeriteItemLocation))
[string "=[C]"]: ?
[string "@Interface\AddOns\AzeriteUI\back-end\plugins\generic_artifactpower.lua"]:111: in function <...AzeriteUI\back-end\plugins\generic_artifactpower.lua:80>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface\AddOns\AzeriteUI\front-end\modules\minimap.lua"]:1541: in function `UpdateBars'
[string "@Interface\AddOns\AzeriteUI\front-end\modules\minimap.lua"]:1616: in function `?'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\message.lua"]:65: in function `Fire'
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\event.lua"]:71: in function <...erface\AddOns\AzeriteUI\back-end\libraries\event.lua:68>

Locals: (*temporary) = <table> {
 GetBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:34
 IsBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:52
 SetEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:38
 HasAnyLocation = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:56
 Clear = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:21
 IsEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:48
 IsEqualToBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:64
 SetBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:27
 IsEqualTo = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:80
 GetEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:44
 IsEqualToEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:72
 slotIndex = 14
 bagID = 3
 IsValid = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:60
}_

### Steps to reproduce  

_Only way I can reproduce the error is to log out (or exit game, either works.) Reloading does not produce the error._

### Expected behaviour  

_Doesn't appear to change the behavior of the UI. Just a random bug._

### Actual behaviour  

_As above._

**Comment by goldpaw** [comment]
Never got around to looking at this report until now, but I'm pretty certain I have fixed this a few days ago. Correct me if I'm wrong.
