### ISSUE TITLE
Druid Legendary breaks Azerite UI's ability to track Lifebloom

### ISSUE THREAD

**Issue by Gellfling** [GoldpawsStuff/AzeriteUI#58]
## The problem  

Lifebloom is a spell that should under normal circumstances only be allowed on one target. The legendary effect "The Dark Titan's Lesson" allows it to be on two targets. When you have the legendary item on and cast Lifebloom on someone, Azerite UI no longer shows Lifebloom in the buffs area.

### Make sure you can check all these boxes  

- [X] I have the latest addon version available from CurseForge.
- [ ] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [X] Retail 
	- [ ] Battle for Azeroth
	- [X] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [X] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [X] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [X] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [X] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Steps to reproduce  

Equip a legendary item that has "The Dark Titan's Lesson" on it

### Expected behaviour  

The buff should show up

### Actual behaviour  

The buff doesn't show up

**Comment by goldpaw** [comment]
Probably a changed auraID of the lifebloom spell when using the legendary. 

This is strictly speaking not a bug, but probably related to aura filter settings. Go to our cogwheel addon menu, and change the aura filter setting to "spam", if it hasn't been automatically changed to that already (which I did in a recent) build.
