### ISSUE TITLE
More Buttons

### ISSUE THREAD

**Issue by supermilho** [GoldpawsStuff/AzeriteUI#59]
**What WoW version do you wish to see this feature in?**
- [ ] Classic
- [x ] Battle for Azeroth

**Is your feature request related to a problem? Please describe.**
I play protection warrior and 17 buttons are not enough to put everything I use in the action bar

**Describe the solution you'd like**
if you can add side buttons or more buttons it would look great

**Describe alternatives you've considered**
Place more buttons (side)

**Additional context**
Anything

**Comment by goldpaw** [comment]
No theme in this UI is restricted to 17. The menu option says "+17", in addition to the 7 that's always there. The UI has 24 buttons when using the azerite theme (/go azerite), and up to 48 using the different legacy theme (/go legacy). 

Anyway, this has already been answered in the download description in all clients and on all webpages: 
https://github.com/GoldpawsStuff/AzeriteUI#how-can-i-get-more-action-buttons-and-where-is-the-stance-bar
