### ISSUE TITLE
Zone Change Resets Chat Window Position [4.0.9-Beta]

### ISSUE THREAD

**Issue by L34Z** [GoldpawsStuff/AzeriteUI#6]
**PROBLEM:** When changing zones the chat window moves to it's default position on the bottom left of the screen, covering the action bars. With the disabling of the edit button it makes it impossible (as far as I can tell) to move it back. 

**STEPS TO REPRODUCE:** Using [4.0.9-Beta](https://www.curseforge.com/wow/addons/azeriteui/files/4120825) change zone change.

**ACTIVE ADDONS:** AzeriteUI 4.0.9-Beta

**EXPECTED BEHAVIOR:** Chat window position should persist through zones.

**Comment by Kaybris** [comment]
Happens especially if there are any chat addons in use e.g Prat.

**Comment by anaarkei** [comment]
I have had this happen to me too.

Temporary workaround: Type /reload into chat

As for why it's happening, my guess is that it is due to behaviour in the deprecated version of the add-on, where the chat window would shift position whenever the action bars were not visible.

**Comment by Goldpaw** [comment]
This was part of a mountain of editmode problems. Should be fixed in 4.0.16.
