### ISSUE TITLE
Lua error unit_groupdebuff

### ISSUE THREAD

**Issue by MegaBlax** [GoldpawsStuff/AzeriteUI#60]
### Make sure you can check all these boxes  

- [x]  I have the latest addon version available from CurseForge.
- [ ] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [x] Retail 
	- [x] Battle for Azeroth
	- [x] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [x] Azerite 
- [x] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [x] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [ ] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [x] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  

LUA ERROR
<details>
Message: ...dOns\AzeriteUI\back-end\plugins\unit_groupdebuff.lua:89: bad argument #1 to 'pairs' (table expected, got nil)

Time: Sun Dec 13 15:05:52 2020
Count: 1
Stack: ...dOns\AzeriteUI\back-end\plugins\unit_groupdebuff.lua:89: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface\AddOns\AzeriteUI\back-end\plugins\unit_groupdebuff.lua"]:89: in function `UpdateClassFilter'
[string "@Interface\AddOns\AzeriteUI\back-end\plugins\unit_groupdebuff.lua"]:96: in main chunk

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
</details>

### Steps to reproduce  

This happens when you enter the command /go legacy, /go azerite, /reloadui

Perhaps adding a check to unit_groupdebuff.lua before line 89 fix the problem?
<body>
<pre>if (not specFilter) then
    return
end
</pre>
</body>

**Comment by goldpaw** [comment]
Should be fixed in 3.1.441-RC.
