### ISSUE TITLE
Bigger Eye of the jayler ui element

### ISSUE THREAD

**Issue by antunes49** [GoldpawsStuff/AzeriteUI#61]
**What WoW version do you wish to see this feature in?**
- [ ] Classic
- [x] Shadowlands

**Is your feature request related to a problem? Please describe.**
The current eye of the jailer is way too small in comparison to the one on blizzard UI and the other elements of the azeriteUI and is harder to see the progress on the bar.

**Describe the solution you'd like**
make it 25% or 50% bigger

**Describe alternatives you've considered**
maybe reposition it to a better place?

**Additional context**
![bigger eye of the jailer](https://user-images.githubusercontent.com/29907925/102153655-79698480-3e56-11eb-83f3-76859439e276.png)

**Comment by goldpaw** [comment]
We made it smaller on request. We're not making it larger on request. If anything, I would remove it completely, as it directly collides with the targeted nameplate on large mobs. 

However. The jailer's eye is part of blizzard's "top center" widget system. Which isn't a system where we really can pick and choose what to style, where to show. Change this, move this, and we also move bg score, island scores, world scores, wsg flag carriers, and so on. So it remains as it is now.
