### ISSUE TITLE
SimpleClassPower and Libs\minimap.lua

### ISSUE THREAD

**Issue by thekreuk** [GoldpawsStuff/AzeriteUI#62]
## The problem  

SimpleClassPower and AzeriteUI conflict, due to AzeriteUI\back-ends\libraries\minimap.lua using different versions.
58 in SimpleClassPower, and 56 in AzeriteUI.

Causes failure to load full AzeriteUI (primarily minimap missing).

Replaced minimap.lua in AzeriteUI with the one from SimpleClassPower, and the error goes away, and the UI fully loads.

### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [x] Retail 
	- [ ] Battle for Azeroth
	- [x] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [x] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [ ] Yes 
- [x] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [x] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [x] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [x] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  

20x ...rfaceAzeriteUI\front-end\modules\minimap.lua:1336: LibMinimap: 'SetMinimapSize' failed, map version too old. Did you forget to call 'SyncMinimap()' first?
[string "=[C]"]: ?
[string "@SimpleClassPower\back-end\libraries\minimap.lua"]:452: in function `SyncMinimap'
[string "@SimpleClassPower\back-end\libraries\minimap.lua"]:687: in function `SetMinimapSize'
[string "@AzeriteUI\front-end\modules\minimap.lua"]:1336: in function `UpdateMinimapSize'
[string "@AzeriteUI\front-end\modules\minimap.lua"]:1590: in function `?'
[string "@AzeriteUI\back-end\libraries\message.lua"]:65: in function `Fire'
[string "@AzeriteUI\back-end\libraries\event.lua"]:71: in function <AzeriteUI\back-end\libraries\event.lua:68>

Locals:
(*temporary) = "LibMinimap: 'SetMinimapSize' failed, map version too old. Did you forget to call 'SyncMinimap()' first?"

### Steps to reproduce  

Install latest versions of SimpleClassPower and AzeriteUI

### Expected behaviour  

Update AzeriteUI\back-ends\libraries\minimap.lua in AzeriteUI?

### Actual behaviour  

N/A

**Comment by goldpaw** [comment]
Fixed
