### ISSUE TITLE
Errors, UI broken

### ISSUE THREAD

**Issue by 40P3** [GoldpawsStuff/AzeriteUI#63]
Disabled all other addons, trying to log in with azerite, getting this error:

Message: ...AzeriteUI\back-end\plugins\generic_artifactpower.lua:111: bad argument #1 to 'GetAzeriteItemXPInfo' (Usage: local xp, totalLevelXP = C_AzeriteItem.GetAzeriteItemXPInfo(azeriteItemLocation))
Time: Fri Dec 25 11:41:30 2020
Count: 1
Stack: ...AzeriteUI\back-end\plugins\generic_artifactpower.lua:111: bad argument #1 to 'GetAzeriteItemXPInfo' (Usage: local xp, totalLevelXP = C_AzeriteItem.GetAzeriteItemXPInfo(azeriteItemLocation))
[string "=[C]"]: ?
[string "@Interface\AddOns\AzeriteUI\back-end\plugins\generic_artifactpower.lua"]:111: in function <...AzeriteUI\back-end\plugins\generic_artifactpower.lua:80>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\minimap.lua"]:195: in function <...face\AddOns\AzeriteUI\back-end\libraries\minimap.lua:189>

Locals: (*temporary) = <table> {
 GetBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:34
 IsBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:52
 SetEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:38
 HasAnyLocation = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:56
 Clear = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:21
 IsEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:48
 IsEqualToBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:64
 SetBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:27
 IsEqualTo = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:80
 GetEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:44
 IsEqualToEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:72
 slotIndex = 16
 bagID = 2
 IsValid = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:60
}

**Comment by goldpaw** [comment]
Sort of missing all the info the issue report template requests. The one that appears when choosing to report an issue. The one that specifically states at the very first lines that it is NOT optional to use. 

I can look into it, but it might take a while.
