### ISSUE TITLE
Cast Bar hidden while using personal resource display

### ISSUE THREAD

**Issue by HoneyBearNathan** [GoldpawsStuff/AzeriteUI#65]
### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge.
- [ ] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [x] Retail 
	- [x] Battle for Azeroth
	- [x] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [x] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [x] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [x] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [x] Druid 
- [x] Hunter 
- [x] Mage 
- [x] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [x] Shaman 
- [ ] Warlock 
- [x] Warrior 

### Any logs, screenshots, error output, etc?  

A) https://i.imgur.com/w2KSG1G.png
B) https://i.imgur.com/OUrgHlp.png
C) https://i.imgur.com/DrlAJcZ.png
### Steps to reproduce  

Have Cast Bar enabled in the HUD options. Have Personal Resource Display on
### Expected behaviour  

I expected the normal hud cast bar to show up even while using Personal Resource Display as is shown in screenshot B but it disappears despite being on in the Azerite UI HUD options
### Actual behaviour  

The on hud static cast bar isn't visible while using Personal Resource Display, but WILL show up if I turn it off, then on again through the Azerite UI HUD options.

**Comment by goldpaw** [comment]
That's actually intended. The castbar and the personal resource display will overlap, and the prd has its own castbar too. 

The bug here is that toggling it in the menu temporarily allows the castbar to be shown while the prd is enabled. So I'll fix that.

**Comment by HoneyBearNathan** [comment]
Then.. you're welcome? I think.. I of course love your UI but would you perhaps update it to have PvP functionality? ie; frames for arena enemies/flag carriers. Aside from that, I think your UI fits perfectly with how I like to enjoy WoW, no need to mess with all that bartender nonsense.
