### ISSUE TITLE
Mail icon's layer level is higher then MinimapButtonBag's button.

### ISSUE THREAD

**Issue by MEndermanM** [GoldpawsStuff/AzeriteUI#67]
### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge.
- [ ] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [x] Retail 
	- [ ] Battle for Azeroth
	- [x] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [x] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Any logs, screenshots, error output, etc?  

![WoWScrnShot_010121_225853](https://user-images.githubusercontent.com/30034564/103441077-71974600-4c86-11eb-83b1-e2aaabbb2f74.jpg)

### Expected behaviour  

It just a sample Layer Level problem.
Also an apologize for it seems I'm so tricky hahah.
But fixing the layer problem may give a blessing for people who have OCD(yup that's me hehe). Thank you!

**Comment by goldpaw** [comment]
It's not a bug, or at least not mine. The mail icon is fine. Right-click the MBB icon, change growth direction to up, make the row 1 wide, change the secondary direction to left, and the icons will start growing from ABOVE the button and towards the left, meaning ABOVE the mail icon. 

Not a bug, just a matter of setting it up. :)
