### ISSUE TITLE
Vehicle UI doesn't appear during questing in Dragonflight

### ISSUE THREAD

**Issue by Kaybris** [GoldpawsStuff/AzeriteUI#7]
None of the vehicle UI shows up. Have to disable AzeriteUI to be able to use the vehicle/mini games UI. Some of the extra quest buttons on screen doesn't show up either. Like using a quest item staff to free time travellers.

**Comment by Goldpaw** [comment]
Probably an editmode problem. Should be fixed in 4.0.16, unless another addon taints the editmode and breaks my secure buttons, which can happen.
