### ISSUE TITLE
UI Rescale

### ISSUE THREAD

**Issue by Zahlos** [GoldpawsStuff/AzeriteUI#7]
**What WoW version do you wish to see this feature in?**
- [ ] Battle for Azeroth

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
I love almost everything about the UI , the only thing I would totally love to see is a rescale option. Because on 2560 x 1440 i feel that the ui  takes up just a little to much of the screen when doing a M+ for example.

**Describe the solution you'd like**
A scale slider in the bottom right menu would be ideal
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. You can list other addons you're using to achieve this here. a dial? 

**Additional context**

Thanks so much for the beautiful UI u make me play wow in an entirely new and exiting way!

**Comment by thedutchglaswegian** [comment]
Oh god yes i agree with this, and maybe a option to colour the gems and healthbar.

**Comment by goldpaw** [comment]
The UI has been specially designed (in all themes) to adjust its sizes based on screen height, as part of our entire mission statement is a unified look regardless of hardware setup. This will not change.
