### ISSUE TITLE
Classic: Error when using the dismount Button

### ISSUE THREAD

**Issue by NoraHub** [GoldpawsStuff/AzeriteUI#70]
## The problem  

When using the dismount button near the minimap. the game throws an error about the function "IsPossessBarVisible" being a nil value. Maybe it's not a part of the classic API? Doesn't bother me too much because I don't usually use that button (I just wanted to try it really), but I still thought this should be brought to your attention.

### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [x] Classic 
- [ ] Retail 
	- [ ] Battle for Azeroth
	- [ ] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [x] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [x] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [x] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [x] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [x] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [x] Warrior 

### Any logs, screenshots, error output, etc?  

Message: ...AddOns\AzeriteUI\back-end\libraries\actionbutton.lua:2059: attempt to call upvalue 'IsPossessBarVisible' (a nil value)
Time: Thu Jan  7 23:32:20 2021
Count: 1
Stack: ...AddOns\AzeriteUI\back-end\libraries\actionbutton.lua:2059: attempt to call upvalue 'IsPossessBarVisible' (a nil value)
...AddOns\AzeriteUI\back-end\libraries\actionbutton.lua:2059: in function <...AddOns\AzeriteUI\back-end\libraries\actionbutton.lua:2056>

Locals: self = <unnamed> {
 0 = <userdata>
 isMouseOver = true
 Point = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:259
 Place = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:233
 CreateTexture = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:327
 CreateStatusBar = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\statusbar.lua:800
 prioritizeGamePadBinds = false
 Chain = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\forge.lua:177
 _owner = <unnamed> {
 }
 CreateFrame = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:317
 SubForge = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\forge.lua:461
 Size = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:279
 PostEnter = <function> defined @Interface\AddOns\AzeriteUI\tinkertown\schematic-actionbars-azerite.lua:593
 prioritzeKeyboardBinds = true
 CreateFontString = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:322
 padStyle = "default"
 texture = <unnamed> {
 }
 CreateOrb = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\orb.lua:503
 Forge = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\forge.lua:241
 Decorate = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\forge.lua:210
 IsForbidden = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:309
 SetProperties = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:292
 CreateSpinBar = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\spinbar.lua:867
}
button = "LeftButton"
(*temporary) = nil
(*temporary) = "attempt to call upvalue 'IsPossessBarVisible' (a nil value)"
IsPossessBarVisible = nil
PetCanBeDismissed = <function> defined =[C]:-1

### Steps to reproduce  

Be mounted and click the dismount button near the minimap

### Expected behaviour  
Dismount without error

### Actual behaviour  
Dismount with error (the dismount still works)

**Comment by goldpaw** [comment]
Ah, yes. That's only meant to be called in the retail version, not the classic version. No possess- or vehiclebars in classic! I'll get it fixed! :o

**Comment by goldpaw** [comment]
Should be fixed in 3.1.449-RC.
