### ISSUE TITLE
Artifact Power Shows on Minimap at max level?

### ISSUE THREAD

**Issue by LefanSnow2070** [GoldpawsStuff/AzeriteUI#72]
**What WoW version do you wish to see this feature in?**
- [ ] Classic
- [x] Shadowlands?

**Is your feature request related to a problem? Please describe.**
Why is it that we still have artifact power on our minimap in shadowlands? What logical purpose does that serve? 

**Describe the solution you'd like**
I feel like Anima would be a fitting replacement for that spot.

**Describe alternatives you've considered**
Or Instead, make a button for your Covenant info.

**Additional context**
This just seems like it should have been implemented and prioritized a while ago.

**Comment by goldpaw** [comment]
You can remove it by simply putting your Heart of Azeroth in one of the additional containers in your bank. Not the main bank slot. Then the Azerite Power information isn't available to the UI, and it is hidden. 

Anima is a currency and can be tracked on the bags, it is not really comparable to Azerite Power, which is a separate system.

**Comment by LefanSnow2070** [comment]
Oh snap, I wasn't aware, Thanks for the fast reply!

**Comment by goldpaw** [comment]
I looked into the blizz code, btw, and will from the next update use the shadowlands logic to decide whether or not it should be visible. :)

**Comment by goldpaw** [comment]
Totally forgot to close this one. Azerite Power is no longer visible at max level in Shadowlands, this has been solved weeks, possibly months ago already! :o
