### ISSUE TITLE
Achievement toast / popup is missing

### ISSUE THREAD

**Issue by shepard02** [GoldpawsStuff/AzeriteUI#74]
## The problem  
The achievement toast window is missing. When I get an achievement, I can see it in the chat, however the main popup window is not showing up. I am also using Narcissus but the issue is present with or without it. I've deleted every addon to double check it with only Azerite UI enabled but the issue still persists. I've tried to toggle the options on and off but if it is a feature I didn't find the option to disable it.

### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge.
- [ ] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [ ] Retail 
	- [ ] Battle for Azeroth
	- [x] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [x] Azerite 
- [x] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [x] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [x] No 

### What classes does it happen on?  

- [x] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [x] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Steps to reproduce  
Easy way to earn an achievement to check this issue is to create two lvl 1 characters and win a duel.

### Expected behaviour  
Achievement toast should be visible.

### Actual behaviour  
No achievement toast window.

**Comment by goldpaw** [comment]
Not a bug. You just need to enable "Alerts" in the HUD section of our menu. Then the achievement toast shows up! :)

![WoWScrnShot_011921_211122](https://user-images.githubusercontent.com/6476535/105087570-f5309f80-5a9a-11eb-8757-b5589d24205e.jpg)

![WoWScrnShot_011921_211117](https://user-images.githubusercontent.com/6476535/105087584-f8c42680-5a9a-11eb-868a-976c4337a2c0.jpg)

**Comment by shepard02** [comment]
Thank you!
