### ISSUE TITLE
Integration with Rider.io addon

### ISSUE THREAD

**Issue by webdevpro-pl** [GoldpawsStuff/AzeriteUI#75]
**What WoW version do you wish to see this feature in?**
- Shadowlands

**Describe the solution you'd like**
Raider.io has a very very popular addon in these days, but it's not compatible with azerite UI. Score and progress info doesn't show on players tooltip.

**Additional context**
![default interface](https://user-images.githubusercontent.com/77788472/105356843-38eaec80-5bf4-11eb-9668-60d53dbf5d69.png)
![azerite interface](https://user-images.githubusercontent.com/77788472/105356848-3a1c1980-5bf4-11eb-92c9-b6c1fc486fd3.png)

**Comment by goldpaw** [comment]
AzeriteUI has from the latest update stopped removing information added by other addons from the WorldFrame mouseover tooltips. So it should in theory be visible there now. 

I will however not add this info to our own unitframe tooltips. Scoring people is kind of not the intention of our UI, and not something I would ever add support for. I won't block it in the non-AzeriteUI parts anymore, though.
