### ISSUE TITLE
Tooltips health bar style is inconsistent

### ISSUE THREAD

**Issue by Mengqyzh** [GoldpawsStuff/AzeriteUI#77]
## The problem  
Tooltips health bar style is inconsistent
I'm not sure if it's because zhcn locale is loaded
### Make sure you can check all these boxes  

- [X] I have the latest addon version available from CurseForge.
- [X] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [X] Retail 
	- [X] Battle for Azeroth
	- [X] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [X] Azerite 
- [X] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [X] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [X] Yes 
- [ ] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [X] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  
![InkedWoWScrnShot_012421_174056_LI](https://user-images.githubusercontent.com/22351255/105626769-fa139b80-5e6c-11eb-8a1d-ece35d43331d.jpg)
![InkedWoWScrnShot_012421_174151_LI](https://user-images.githubusercontent.com/22351255/105626776-07c92100-5e6d-11eb-86cb-326a2a23de53.jpg)

**Comment by goldpaw** [comment]
Not actually a bug. We use bigger bars in the tooltips connected to our own unitframes, while the tooltips generated by the game when mousing over a unit in the world has smaller bars. The main reason for this is that we can't change the size or layout of the worldframe tooltips much, as these belong to blizzard and follow stricter rules, so we make the bars smaller to fit. 

It's not a bug, in other words. It's different layouts in different tooltips.
