### ISSUE TITLE
Objectives tracker makeover.

### ISSUE THREAD

**Issue by Aequitas21541** [GoldpawsStuff/AzeriteUI#78]
**What WoW version do you wish to see this feature in?**
- [x] Classic
- [x] Battle for Azeroth

**Is your feature request related to a problem? Please describe.**
Objective tracker consistent with the rest of the UI.

**Describe the solution you'd like**
![tracker](https://user-images.githubusercontent.com/55895364/105760472-235a2780-5f52-11eb-8d98-dcbed02b2ba2.png)

**Describe alternatives you've considered**
Option to disable the tracker completely.

**Comment by goldpaw** [comment]
If I do a make over, it would be to make the retail tracker look like our classic tracker, which are not the same ones. I would in other words NOT add more buttons, thicker borders, that kind of thing. I would remove instead, make it simpler. 

As for the option to disable the tracker, that's in the addon already. Under cogwheel > HUD.
