### ISSUE TITLE
Hey guys i´m fancy with your job . 

### ISSUE THREAD

**Issue by AndresRv20** [GoldpawsStuff/AzeriteUI#8]
I have a problem with the other addons of interface , simplieilvl , tinyinspect I don´t see item lvl or IO of other players please fix this bug !! Wait for answer

**Comment by joshbowman** [comment]
In a similar vein, I noticed since updating to the most recent version of AzeriteUI for retail that additional info in tooltips from Rarity no longer displays.  It would be great to have that back.
