### ISSUE TITLE
Minimap quest zone

### ISSUE THREAD

**Issue by invocador18** [GoldpawsStuff/AzeriteUI#82]
## The problem  
Blue quest zone and world quest zone on minimap don't show

### Make sure you can check all these boxes  
- [x] I have the latest addon version available from CurseForge.
- [ ] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [x] Retail 
	- [ ] Battle for Azeroth
	- [x] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [x] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [x] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [x] Yes 
- [ ] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [x] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Steps to reproduce  

Questing

### Expected behaviour  
The quest zone on minimap should show

### Actual behaviour  
The minimap just doesn't delimit the quest area

**Comment by goldpaw** [comment]
To make anything show in the worldmap, you have to click the round numbered POI-button next to the quest in the quest tracker. This is standard behavior even without AzeriteUI.

As for the minimap, it does show the blue blob outline around quest areas. Not fully covering the inside of it as well is a choice, not a bug.
