### ISSUE TITLE
Lua Errors in dungeons (global colour error)

### ISSUE THREAD

**Issue by Kimshoui** [GoldpawsStuff/AzeriteUI#87]
## The problem  

When I'm in dungeon, fighting against enemies that have a lot of habilities and effects, a Lua error appears

### Make sure you can check all these boxes  

- [X] I have the latest addon version available from CurseForge.
- [X] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [X] Retail 
	- [ ] Battle for Azeroth
	- [X] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [X] Azerite 
- [ ] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [X] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [X] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [X] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, screenshots, error output, etc?  

The Lua Error : 

Message: ...erface\AddOns\AzeriteUI\front-end\config\configs.lua:3959: attempt to index global 'colors' (a nil value)
Time: Sun Mar 28 12:52:46 2021
Count: 39
Stack: ...erface\AddOns\AzeriteUI\front-end\config\configs.lua:3959: attempt to index global 'colors' (a nil value)
[string "@Interface\AddOns\AzeriteUI\front-end\config\configs.lua"]:3959: in function <...erface\AddOns\AzeriteUI\front-end\config\configs.lua:3942>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface\AddOns\AzeriteUI\back-end\libraries\widgetcontainer.lua"]:203: in function <...Ons\AzeriteUI\back-end\libraries\widgetcontainer.lua:197>

Locals: element = <unnamed> {
Overlay = <unnamed> {
}
Point = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:262
guid = "Player-512-09CDE663"
elapsed = 0.043000
duration = 4
OnBackdropLoaded = <function> defined @Interface\SharedXML\Backdrop.lua:195
expirationTime = 145468.353000
CreateStatusBar = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\statusbar.lua:800
GetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:433
Time = <unnamed> {
}
_owner = GP_WidgetContainer_9463 {
}
CreateFrame = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:320
PostUpdate = <function> defined @Interface\AddOns\AzeriteUI\front-end\config\configs.lua:3942
ApplyBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:337
SetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:372
ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:325
spellID = 321821
GetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:452
GetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:390
debuffType = "Disease"
type = "Boss"
index = 1
Cooldown = <unnamed> {
}
CreateSpinBar = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\spinbar.lua:867
SetBorderBlendMode = <function> defined @Interface\SharedXML\Backdrop.lua:309
Place = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:236
CreateTexture = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:330
CreateOrb = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\orb.lua:503
unit = "party2"
timeLeft = 0.150000
disableMouse = true
OnBackdropSizeChanged = <function> defined @Interface\SharedXML\Backdrop.lua:225
HasBackdropInfo = <function> defined @Interface\SharedXML\Backdrop.lua:321
priority = 0
Icon = <unnamed> {
}
Size = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:282
timeStarted = 145464.353000
GetEdgeSize = <function> defined @Interface\SharedXML\Backdrop.lua:231
fullDuration = 4
ForceUpdate = <function> defined @Interface\AddOns\AzeriteUI\back-end\plugins\unit_groupdebuff.lua:437
Border = <unnamed> {
}
IsForbidden = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:312
CreateFontString = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:325
0 = <userdata>
SetupTextureCoordinates = <function> defined @Interface\SharedXML\Backdrop.lua:257
SetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:465
Count = <unnamed> {
}
filter = "HARMFUL"
SetupPieceVisuals = <function> defined @Interface\SharedXML\Backdrop.lua:289
SetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:442
SetProperties = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:295
GetFrame = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:231
}
unit = "party2"
self = GP_WidgetContainer_9463 {
0 = <userdata>
OnEnter = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\unitframe.lua:242
Point = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\frame.lua:262
ReadyCheck = <unnamed> {
}
OnBackdropLoaded = <function> defined @Interface\Sha

A screenshot of the error appearing : 
![image](https://user-images.githubusercontent.com/63460018/112769886-eaa6ff00-9023-11eb-8986-f0cd5fa6d446.png)

### Steps to reproduce  

Just have to fight in dungeon (probably happpening in raids too)

### Expected behaviour  

KILLING every entity in the dungeon !

### Actual behaviour  

KILLING every entity in the dungeon ! But with Lua Errors appearing at every fight ^^

Thanks for your time ! :D

**Comment by goldpaw** [comment]
Should be fixed in 3.2.464-RC.
