### ISSUE TITLE
Error Temple of Sethraliss

### ISSUE THREAD

**Issue by Shemhazai66** [GoldpawsStuff/AzeriteUI#89]
Message: Interface\AddOns\AzeriteUI\back-end\tools\chat.lua:448: invalid option in `format'
Time: Thu Apr  1 14:02:31 2021
Count: 1
Stack: Interface\AddOns\AzeriteUI\back-end\tools\chat.lua:448: invalid option in `format'
[string "=[C]"]: ?
[string "@Interface\AddOns\AzeriteUI\back-end\tools\chat.lua"]:448: in function <Interface\AddOns\AzeriteUI\back-end\tools\chat.lua:447>
[string "@Interface\AddOns\AzeriteUI\back-end\tools\chat.lua"]:619: in function `filterFunc'
[string "@Interface\FrameXML\ChatFrame.lua"]:3489: in function `ChatFrame_MessageEventHandler'
[string "@Interface\FrameXML\ChatFrame.lua"]:3063: in function `ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: (*temporary) = "Аватара очищена от [порчи]! Ваши исцеляющие способности эффективны на 100%!"
(*temporary) = "Аватара Сетралисс"

On hovering over Sethraliss when the corruption wears off

Azerite UI (Retail)

**Comment by goldpaw** [comment]
Hovering over the frame probably had nothing to do with it. Looking at the code, it looks like a boss emote triggered the bug. 

I can see the bug in my code, though. I think it's a remnant from the WoW classic code, which just doesn't work the same way in retail. I'll get right to it!

**Comment by Shemhazai66** [comment]
Ok, this is not critical, I just decided to write about it

**Comment by goldpaw** [comment]
Should be fixed in 3.2.466-RC
