### ISSUE TITLE
RaidFrames :/ still gone

### ISSUE THREAD

**Issue by sibbigali** [GoldpawsStuff/AzeriteUI#9]
i have got a little problem - my raidframes are still gone

`2x ...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:484: Usage: GetRaidProfileOption("profile", "optionName")
[string "=[C]"]: in function `GetRaidProfileOption'
[string "@Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:484: in function `initFunction'
[string "@FrameXML\UIDropDownMenu.lua"]:76: in function `UIDropDownMenu_Initialize'
[string "@Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:472: in function `CompactUnitFrameProfilesDropdown_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:28: in function `InterfaceOptionsList_DisplayPanel'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:46: in function `InterfaceOptionsListButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = nil
(*temporary) = "sortBy"
` 
this is what buggrabby says , any idea ?

**Comment by JasonQWJ** [comment]
me to

**Comment by goldpaw** [comment]
Weirdness, looking into this.

**Comment by goldpaw** [comment]
Solved by NOT allowing the default blizzard raid frames together with the UI. This was only an experimental feature to begin with, and seeing how new bugs and addon incompatibilities just keep popping up every few weeks, I'm removing the option to combine default frames of any kinds with the UI. 

The UI will continue to work flawlessly with other 3rd party raid addons like Grid.

**Comment by goldpaw** [comment]
And just to update, that did NOT solve the bug, I misunderstood the issue slightly. It IS however fixed in the latest builds. So go update! :+1:
