### ISSUE TITLE
Can't see focus

### ISSUE THREAD

**Issue by calbright98** [GoldpawsStuff/AzeriteUI#94]
Whenever I want to focus anything no focus frame becomes visible. I've tried right clicking on portraits and using macros

**Comment by calbright98** [comment]
Make sure you can check all these boxes
 I have the latest addon version available from CurseForge.
 I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)
What game version(s) does it happen in? Choose your version and the highest expansion you own.
 Classic
[x ] Retail
 Battle for Azeroth
[ x] Shadowlands
 Public Test Realm
 Classic
[x ] Retail
What addon theme(s) does it happen in?
[ x] Azerite
[ ] Legacy
Does this happen with ONLY this addon enabled?
[ x] Yes
[ ] No
Does this happen with absolutely all addons (this included) disabled?
 Yes
[x ] No
What classes does it happen on?
[x ] Death Knight
 Demon Hunter
 Druid
 Hunter
 Mage
 Monk
 Paladin
 Priest
 Rogue
 Shaman
 Warlock
 Warrior
Any logs, screenshots, error output, etc?
Steps to reproduce
Try to set a focus on any target
Expected behaviour
A focus frame should appear somewhere on my UI
Actual behaviour
No focus frame seems to appear at all

**Comment by goldpaw** [comment]
Try looking right above the player frame health bar.

**Comment by calbright98** [comment]
I don't see it there even when Azerite UI is the only addon enabled

**Comment by goldpaw** [comment]
Yeah. Definitely gone. Got to my computer, verified it and working on it now. :o

**Comment by goldpaw** [comment]
Ah. Found the problem. It checks for retail before the flag indicating retail has been set. Complete rookie mistake by me. Fix coming right up! :)

**Comment by goldpaw** [comment]
Fixed in 3.2.477-Release
