### ISSUE TITLE
More action buttons

### ISSUE THREAD

**Issue by nasilvera** [GoldpawsStuff/AzeriteUI#95]
**What WoW version do you wish to see this feature in?**
- [ ] Classic
- [x] Shadowlands

**Is your feature request related to a problem? Please describe.**
Some classes have a ton of buttons I like to see my abilities.

**Describe the solution you'd like**
Just a few more buttons there's a large blank spot betwenn the current buttons and the minimap that could be filled with optional buttons.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. You can list other addons you're using to achieve this here.

**Additional context**

**Comment by goldpaw** [comment]
There is no room, that space is for text, vehicle seat, durability, tons of things. 

On the question of more buttons, that has already been answered on the download pages, both here, on curseforge and in the client:  

https://github.com/GoldpawsStuff/AzeriteUI#how-can-i-get-more-action-buttons-and-where-is-the-stance-bar
