### ISSUE TITLE
Party frames disappears after reload

### ISSUE THREAD

**Issue by wesayno** [GoldpawsStuff/AzeriteUI#96]
## The problem  

**The partyframes disappear on every reload/loading screen, and only reappears if i disable and re-enable the party frames in the "unit frames" option.**

### Make sure you can check all these boxes  

- [x] I have the latest addon version available from CurseForge.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- [ ] Classic 
- [x] Retail 
	- [ ] Battle for Azeroth
	- [x] Shadowlands 
- [ ] Public Test Realm 
	- [ ] Classic 
	- [ ] Retail 

### What addon theme(s) does it happen in?  

- [ ] Azerite 
- [x] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [x] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [x] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [x] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [x] Warlock 
- [ ] Warrior 

### Expected behaviour  

I guess party frames should always be visible as long as im in a party and stay put through reloads.

### Actual behaviour  

All party unit frames disappear on every reload or loading screen, and doesnt come back unless i turn unit frames off and on again. They disappear again on next loading screen.

**Comment by goldpaw** [comment]
I smell a problem related to the menu option I added recently. I'll look into it!

**Comment by goldpaw** [comment]
Found the problem. Was a typo in the script that loads the saved setting for party frames. Will be fixed in the next update! :)

**Comment by goldpaw** [comment]
Hopefully fixed in 3.2.480-Release.
