### ISSUE TITLE
Burning Crusade: XP bar is missing from mini-map

### ISSUE THREAD

**Issue by Tr4m4h4wK** [GoldpawsStuff/AzeriteUI#97]
XP Bar is absent from Mini-map. thanks for your great work!

**Comment by Gracelyte** [comment]
Same problem here.  Did you remove it, replaced somewhere, or smiplely is a bug. thx ！ great work by the way!

**Comment by goldpaw** [comment]
Fixed in 3.2.486-RC! :)
