### ISSUE TITLE
Battleground Conflict on BCC 3.2.486

### ISSUE THREAD

**Issue by Tr4m4h4wK** [GoldpawsStuff/AzeriteUI#99]
Hi, great work! Having an issue when queue for Battleground happens, i have to disable AzeriteUI in order to enter battleground everytime.

**Comment by goldpaw** [comment]
Probably the same bug as in wow for classic era. I'll add the same fix/workaround to the tbc version! :+1:

**Comment by goldpaw** [comment]
Should be fixed in 3.2.487-RC, available shortly.
